import { Eyebrow, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';

export const metadata = pageMetadata(
  'Terms of Service | SeekAPI',
  'Terms for SeekAPI China Supply Check, Live RFQ Compare, MCP tools and related sourcing services.',
  '/terms',
);

export default function Page() { return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>Terms of Service · Effective September 30, 2026</Eyebrow><h1>Clear scope before payment. Evidence before claims.</h1><p>These Terms govern seekapi.ai, the SeekAPI public MCP endpoint and related services operated by SeekAPI Technology Limited. By using a service, you agree to the applicable scope shown at confirmation or purchase.</p></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="China Supply Check" title="A paid sourcing-screening service." body="China Supply Check is priced at 2.99 USDC per accepted check unless a production interface states a different current price. You provide one product or model, quantity and unit, and must-have specifications. On a successful completed check, SeekAPI returns three distinct qualified China B2B platform-shop candidates with source-linked observed listing price, MOQ and quantity fit, specification match or UNKNOWN, exclusions and an editable RFQ starting point."/><p>If fewer than three candidates can be supported within the purchased search scope, SeekAPI reports the shortage rather than inventing suppliers. An accepted order may be completed through automated or human-assisted operations; the purchased scope and evidence standard remain the same.</p></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Evidence boundary" title="A listing is not a quotation or manufacturer verification." body="An observed listing price is a dated marketplace observation, not a current supplier quotation or EXW price. A platform shop is not independently verified by SeekAPI as the legal manufacturer. Listing information does not establish current stock, production capacity, lead time, certification or willingness to supply unless the result contains direct evidence for that claim."/></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Live RFQ Compare" title="A separate paid supplier-response service." body="Live RFQ Compare is priced at USD 19.90 unless the production interface states a different current price. You edit and confirm one RFQ and select up to three recipients. After payment and authorization, SeekAPI performs one human outreach round and allows a 72-hour response window for current price, availability, MOQ and lead time. Supplier response is not guaranteed."/></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Orders and payment" title="Payment authorizes only the purchased scope." body="The order confirmation identifies the service, price, payment method and authorized scope. Payment for China Supply Check does not authorize supplier contact. Payment for Live RFQ Compare authorizes only the confirmed RFQ, selected recipients and stated outreach scope. SeekAPI may use automated or assisted fulfillment behind the service without changing the customer-facing contract."/><p>Confirmed duplicate or unauthorized charges, and accepted orders that SeekAPI cannot perform, will receive an appropriate remedy. An honest result that reports no qualifying candidates within the defined search scope is not automatically a service failure. Nothing in these Terms limits non-waivable rights under applicable law.</p></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Third-party information" title="Source material can be incomplete or stale." body="Marketplace and third-party data may contain errors, omissions or outdated information. SeekAPI identifies source observations, exclusions and UNKNOWNs where reasonably possible, but users remain responsible for final purchasing, supplier verification, technical suitability, product safety, import/export, customs, tax and regulatory decisions."/></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Acceptable use" title="Do not misuse the service." body="Users and Agents must not use SeekAPI to violate law or third-party rights, obtain unauthorized access, bypass access controls or payment requirements, interfere with service operation, or submit credentials and secrets that are not required for the purchased task."/></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Intellectual property and availability" title="Use results for your procurement work." body="SeekAPI retains rights in its software, service design, documentation, compilation and analysis. Third-party trademarks, marketplace content and source material remain subject to their respective owners. SeekAPI may update or suspend a feature where reasonably necessary for maintenance, security, compliance or product development."/></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Liability and law" title="The service supports a sourcing decision; it does not replace required professional judgment." body="To the maximum extent permitted by applicable law, SeekAPI is not responsible for indirect or consequential losses caused by third-party marketplace information or transactions independently entered into with suppliers. Nothing excludes liability that cannot lawfully be excluded. These Terms are governed by the laws of the Hong Kong Special Administrative Region, subject to mandatory rights under applicable law."/></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Contact" title="SeekAPI Technology Limited" body="Room P11, Flat 2C, 2/F, Hung To Ctr., 94–96 How Ming St., Kwun Tong, Kowloon, Hong Kong · support@seekapi.ai"/></div></section>
</PageShell>; }
