import Link from 'next/link';
import { Eyebrow, PageShell } from '@/components/site';
import { pageMetadata } from '@/lib/site';

export const metadata = pageMetadata('Service Terms', 'China Supply Check order, delivery, evidence and authorization boundaries from SeekAPI Technology Limited.', '/terms');

export default function TermsPage() { return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>Service terms</Eyebrow><h1>Know what an accepted China Supply Check order buys.</h1><p>These terms are offered by SeekAPI Technology Limited for SeekAPI services described here. Contact <a className="text-link" href="mailto:support@seekapi.ai">support@seekapi.ai</a> about an order or a service concern. An individual order can state additional scope and payment details before you approve it.</p><p>Version 1 · 30 September 2026</p></div></section>
  <section className="section"><div className="container"><h2>Free preparation and order acceptance</h2><p>Public MCP discovery and Product Brief preparation are free. A prepared draft or support email does not buy a service, accept an order, authorize payment or contact a supplier. A China Supply Check purchase is accepted only after the buyer confirms the exact brief and SeekAPI confirms the supported payment path, amount and order reference. The website page itself does not collect payment. Do not treat a payment challenge or an arbitrary order ID as a completed purchase.</p></div></section>
  <section className="section section-dark"><div className="container"><h2>China Supply Check · 2.99 USDC</h2><p>The service screens China B2B platform-shop listings for one confirmed product or model, quantity and hard specifications. On a successful completed check, the report documents three distinct qualifying shop candidates with source links, observation times, displayed listing-price basis, MOQ and specification fit, exclusions and unknowns. If three cannot be supported, the report states the shortage and its evidence instead of inventing candidates. Price, network and any other payment terms for an actual order are shown through its supported acceptance path before payment.</p><p>An accepted paid order is fulfilled and its result made available to the authorized buyer. If automated fulfillment is unavailable, SeekAPI may complete the same bounded service manually. If we cannot deliver the purchased service, contact support with the order reference; SeekAPI will complete delivery or resolve the undelivered service fee through the supported order path. Do not send a wallet secret or bearer payment proof by email.</p></div></section>
  <section className="section"><div className="container"><h2>Evidence is not a supplier promise</h2><p>A dated listing price is published supplier commercial evidence with its currency, unit, tier and quantity conditions, not a confirmed reply for your exact RFQ or an EXW term. Certification, company-registration, production-versus-trade identity, stock, current MOQ, lead time and the available shop or listing contact path are reported per candidate when the listing or a bound source provides them; fields without such evidence are marked for that candidate, and a confirmed direct reply is distinct from an available contact. The archived historical V4 sample is a separate evidence-format example preserved for provenance; it is not a completed customer paid order.</p></div></section>
  <section className="section section-dark"><div className="container"><h2>Authority and separate services</h2><p>China Supply Check does not authorize supplier contact, an RFQ, a payment to a supplier, a contract change or acceptance of a quality deviation. The separate Live RFQ Compare service, if offered for purchase, requires its own confirmed RFQ, selected recipients, payment and explicit human outreach authorization. Replies are not guaranteed. You must have the right to share the brief you provide and should not submit restricted, unlawful or sensitive information without an agreed handling scope.</p></div></section>
  <section className="section"><div className="container"><h2>Questions and changes</h2><p>For a report, payment or delivery issue, contact <a className="text-link" href="mailto:support@seekapi.ai">support@seekapi.ai</a> with the order reference and the observed problem. SeekAPI Technology Limited can be reached at Room P11, Flat 2C, 2/F, Hung To Ctr., 94–96 How Ming St., Kwun Tong, Kowloon, Hong Kong. Changes to these published terms apply to later orders; an accepted order keeps the scope confirmed at acceptance unless both sides agree otherwise.</p><p><Link className="text-link" href="/privacy">Read the privacy notice</Link> · <Link className="text-link" href="/support">Contact support</Link></p></div></section>
</PageShell>; }
