import { CTA, Eyebrow, FeatureCard, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';
export const metadata=pageMetadata('Proof and Examples','How SeekAPI separates verified cases, self-funded demonstrations, public analysis and illustrative workflows.','/proof');
export default function Page(){return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>Evidence before claims</Eyebrow><h1>Proof should say exactly what it proves.</h1><p>This preview contains method examples, not invented customer history. Real customer cases, performance figures and partner claims appear only when evidence and publication permission exist.</p></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Evidence classes" title="Four labels with different meanings."/><div className="grid-2"><FeatureCard title="Verified customer case" body="A real SeekAPI engagement published with appropriate evidence and permission. No asset is published in this preview."/><FeatureCard title="Self-funded SeekAPI demo" body="A real task funded and executed by SeekAPI, clearly identified as a demonstration. No asset is published in this preview."/><FeatureCard title="Public industry analysis" body="Research based on cited public evidence; it does not become a client-delivery claim."/><FeatureCard title="Illustrative workflow" body="A hypothetical example that explains method, decisions and limitations without claiming execution."/></div></div></section>
  <section className="section section-dark" id="quote-example"><div className="container"><SectionTitle eyebrow="Illustrative workflow 01" title="The lower unit price can produce the higher comparable total." body="Assume Supplier A quotes $8.20 per unit plus $4,000 tooling and Supplier B quotes $9.10 with tooling included, both for 1,000 units. Before freight, duty and financing, A totals $12,200 while B totals $9,100."/><div className="grid-3"><FeatureCard title="Inputs" body="Same revision, quantity and scope; hypothetical prices; packaging and terms still require normalization."/><FeatureCard title="Decision" body="Do not select A from unit price alone. Ask what tooling includes, normalize terms and expose missing costs."/><FeatureCard title="Limit" body="This proves the comparison method only. It is not a quote, supplier recommendation, saving claim or customer case."/></div></div></section>
  <section className="section" id="no-go-example"><div className="container"><SectionTitle eyebrow="Illustrative workflow 02" title="China is not always the better sourcing route." body="Assume a small order has modest unit savings but adds freight, inspection, coordination, import uncertainty and a longer replenishment cycle."/><div className="grid-3"><FeatureCard title="Inputs" body="Quantity, timing, freight, working capital and the cost of delay must be included."/><FeatureCard title="Decision" body="When total risk and coordination outweigh the saving, recommend local supply or stop the China route."/><FeatureCard title="Limit" body="The conclusion applies only to stated assumptions. It is not evidence that a specific project was completed."/></div></div></section>
  <CTA title="Judge the method before trusting a claim." body="Start with one issue and require evidence for the next decision." primaryHref="/start?audience=company" secondaryLabel="Trust model" secondaryHref="/trust"/>
</PageShell>}
