import Link from 'next/link';
import { Eyebrow, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';

export const metadata = pageMetadata(
  'China Supplier Search Options and Their Evidence | SeekAPI',
  'Compare marketplace search, RFQ requests, AI sourcing workflows and a bounded listing-evidence check. Vendor features are dated public claims, not independent quality rankings.',
  '/china-supply-check/alternatives',
);

export default function Page() { return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>Workflow comparison · checked 29 September 2026</Eyebrow><h1>Choose the tool that answers your next sourcing question.</h1><p>Free catalog search, marketplace RFQs and managed sourcing already exist. The difference to inspect is whether you need exploratory listings, an evidence-screened shortlist or a direct current supplier response. This page makes no ranking or savings claim.</p></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Available workflows" title="Search, screen and quote are different steps."/><div className="definition-grid"><div className="definition"><h3>Marketplace search</h3><p><a className="text-link" href="https://www.alibaba.com/">Alibaba.com</a> and <a className="text-link" href="https://sourcing.made-in-china.com/">Made-in-China</a> offer supplier/product discovery and RFQ flows. Their listing text is still distinct from a direct reply to your exact request.</p></div><div className="definition"><h3>AI sourcing exploration</h3><p><a className="text-link" href="https://www.accio.com/about-us">Accio</a> describes an AI sourcing workflow with a free entry plan. <a className="text-link" href="https://www.sourceready.com/mcp">SourceReady</a> describes supplier workflows and MCP access. Check their current scope and terms directly.</p></div><div className="definition"><h3>SeekAPI China Supply Check</h3><p>A 2.99 USDC completed check for one accepted product/model and quantity: three distinct qualified B2B shop candidates with source-linked observed price, MOQ/specification evidence, exclusions and unknowns. Free Product Brief preparation is live; a paid order requires separate scope and payment confirmation.</p></div><div className="definition"><h3>Direct current response</h3><p>Marketplace RFQ or supplier outreach can ask for a current quote, stock and lead time. SeekAPI's separate USD 19.90 Live RFQ Compare is planned but unavailable. No platform listing by itself confirms these facts.</p></div></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Evidence limit" title="Vendor pages are not a controlled outcome test." body="Feature descriptions above come from the linked vendors as viewed on 29 September 2026; pricing and availability can change. We did not independently compare supplier response quality or claim unique inventory."/><div className="link-list"><Link className="text-link" href="/china-supply-check/sample">Inspect SeekAPI's sample summary and limits</Link><Link className="text-link" href="/china-supply-check">Read the product contract</Link></div></div></section>
</PageShell>; }
