import { PageShell } from '@/components/site';
import { copy } from '@/lib/inquiries/translations';
import { locales,type Locale } from '@/lib/inquiries/core';
export const metadata={title:'Inquiry privacy — SeekAPI',robots:{index:false,follow:false},alternates:{canonical:null}};
export const dynamic='force-dynamic';
const policy:Record<Locale,string[]>={
 en:['Inquiry privacy','We use your contact details, request and attachments to assess your needs and communicate with you. Sharing information is permission for internal review, not permission to contact suppliers or forward your files. Ask us to agree an NDA before sending confidential materials if necessary. Do not submit passwords, payment-card details or identity documents.','When online intake is enabled, records and private attachments are stored with Supabase. Authorized staff can access them; attachments must pass checks before download. Transactional notifications use Resend. Your materials are not automatically sent to public AI models.','Abandoned uploads are removed after 24 hours. Closed and spam inquiries are scheduled for deletion after 12 months; contractual records may require separate retention agreed for the project. Backups and provider email logs follow the configured provider retention. Contact support@seekapi.ai to request access, correction or deletion.'],
 ja:['問い合わせ情報の取り扱い','連絡先、依頼内容、添付資料は、ご要望の確認と連絡に利用します。共有は社内確認への同意であり、サプライヤーへの連絡や資料転送の許可ではありません。必要に応じて機密資料の送付前にNDAをご相談ください。パスワード、決済カード情報、本人確認書類は送らないでください。','オンライン受付が有効な場合、記録と非公開の添付資料をSupabaseに保存します。許可された担当者のみがアクセスでき、添付資料は検査後にダウンロードできます。通知メールにはResendを使用します。資料を公開AIモデルに自動送信しません。','未完了のアップロードは24時間後に削除します。終了済み・迷惑問い合わせは12か月後に削除予定です。契約記録の保存期間は案件ごとに別途定める場合があります。バックアップとメールログには各提供者の設定が適用されます。開示・訂正・削除のご依頼は support@seekapi.ai へ。'],
 es:['Privacidad de consultas','Usamos sus datos de contacto, solicitud y archivos para evaluar sus necesidades y comunicarnos con usted. Compartirlos permite una revisión interna, no contactar con proveedores ni reenviar archivos. Si necesita un acuerdo de confidencialidad, solicítelo antes de enviar información confidencial. No envíe contraseñas, tarjetas de pago ni documentos de identidad.','Cuando la recepción en línea está habilitada, los registros y archivos privados se guardan en Supabase. Solo el personal autorizado puede acceder; los archivos deben superar controles antes de descargarse. Las notificaciones usan Resend. No enviamos automáticamente sus materiales a modelos públicos de IA.','Las cargas abandonadas se eliminan después de 24 horas. Las consultas cerradas y el spam se programan para eliminación a los 12 meses; los registros contractuales pueden tener otro plazo acordado. Las copias de seguridad y registros de correo siguen la configuración del proveedor. Para acceso, corrección o eliminación: support@seekapi.ai.'],
 ar:['خصوصية الاستفسارات','نستخدم بيانات التواصل والطلب والمرفقات لتقييم احتياجاتك والتواصل معك. المشاركة تسمح بالمراجعة الداخلية ولا تجيز التواصل مع الموردين أو إعادة توجيه ملفاتك. اطلب اتفاقية سرية قبل إرسال مواد سرية عند الحاجة. لا ترسل كلمات المرور أو بيانات بطاقات الدفع أو وثائق الهوية.','عند تفعيل الاستقبال الإلكتروني، تُحفظ السجلات والمرفقات الخاصة لدى Supabase ويصل إليها الموظفون المخولون فقط. يجب فحص المرفقات قبل تنزيلها. تستخدم رسائل الإشعار Resend. لا تُرسل موادك تلقائياً إلى نماذج ذكاء اصطناعي عامة.','تُحذف عمليات الرفع غير المكتملة بعد 24 ساعة. تُجدول الاستفسارات المغلقة والمزعجة للحذف بعد 12 شهراً، وقد تخضع سجلات العقود لمدة أخرى متفق عليها. تتبع النسخ الاحتياطية وسجلات البريد إعدادات مزود الخدمة. لطلب الوصول أو التصحيح أو الحذف: support@seekapi.ai.'],
 de:['Datenschutz für Anfragen','Wir verwenden Kontaktdaten, Anfrage und Anhänge zur Bedarfsprüfung und Kommunikation. Die Übermittlung erlaubt eine interne Prüfung, keine Lieferantenkontaktaufnahme oder Weitergabe Ihrer Dateien. Vereinbaren Sie bei Bedarf vorab eine NDA. Übermitteln Sie keine Passwörter, Zahlungskartendaten oder Ausweisdokumente.','Bei aktivierter Online-Annahme werden Datensätze und private Anhänge bei Supabase gespeichert. Nur befugte Mitarbeiter erhalten Zugang; Dateien müssen vor dem Download geprüft werden. Benachrichtigungen erfolgen über Resend. Materialien werden nicht automatisch an öffentliche KI-Modelle gesendet.','Abgebrochene Uploads werden nach 24 Stunden entfernt. Geschlossene und Spam-Anfragen werden nach 12 Monaten zur Löschung vorgesehen; für Vertragsunterlagen können gesonderte Fristen gelten. Backups und E-Mail-Protokolle unterliegen den Anbietereinstellungen. Auskunft, Berichtigung oder Löschung: support@seekapi.ai.'],
 'pt-BR':['Privacidade das consultas','Usamos seus contatos, solicitação e arquivos para avaliar suas necessidades e nos comunicar com você. O envio permite análise interna, não contato com fornecedores ou encaminhamento dos arquivos. Solicite um acordo de confidencialidade antes de enviar materiais sigilosos, se necessário. Não envie senhas, dados de cartões ou documentos de identidade.','Quando o recebimento on-line está habilitado, os registros e anexos privados ficam no Supabase, acessíveis apenas à equipe autorizada. Os anexos passam por verificações antes do download. As notificações usam Resend. Seus materiais não são enviados automaticamente a modelos públicos de IA.','Uploads abandonados são removidos após 24 horas. Consultas encerradas e spam são programados para exclusão após 12 meses; registros contratuais podem ter prazo específico. Backups e registros de e-mail seguem a configuração do provedor. Para acesso, correção ou exclusão: support@seekapi.ai.'],
 ru:['Конфиденциальность запросов','Контакты, запрос и вложения используются для оценки потребностей и связи с вами. Передача разрешает внутреннюю проверку, но не контакт с поставщиками или пересылку файлов. При необходимости согласуйте NDA до отправки секретных материалов. Не отправляйте пароли, данные платёжных карт или удостоверения личности.','При включённом онлайн-приёме записи и закрытые вложения хранятся в Supabase. Доступ имеет только уполномоченный персонал; вложения проверяются до скачивания. Для уведомлений используется Resend. Материалы не отправляются автоматически в публичные модели ИИ.','Незавершённые загрузки удаляются через 24 часа. Закрытые запросы и спам планируются к удалению через 12 месяцев; договорные записи могут иметь отдельный срок хранения. Резервные копии и почтовые журналы подчиняются настройкам провайдера. Запросы на доступ, исправление или удаление: support@seekapi.ai.']
};
export default async function Page({searchParams}:{searchParams:Promise<{lang?:string}>}){const params=await searchParams;const locale=locales.includes(params.lang as Locale)?params.lang as Locale:'en';const p=policy[locale];return <PageShell><section className="section"><div className="container" lang={locale} dir={locale==='ar'?'rtl':'ltr'}><h1>{p[0]}</h1>{p.slice(1).map(t=><p key={t}>{t}</p>)}<p>Supabase: {process.env.INQUIRY_STORAGE_REGION_LABEL||'Not configured / online intake not enabled'}</p><p>SeekAPI Technology Limited · <a href="mailto:support@seekapi.ai">support@seekapi.ai</a></p><p>{copy[locale].boundary}</p></div></section></PageShell>;}
