import { PageShell } from '@/components/site';
import { copy } from '@/lib/inquiries/translations';
import { locales,type Locale } from '@/lib/inquiries/core';
export const metadata={title:'Inquiry privacy — SeekAPI',robots:{index:false,follow:false},alternates:{canonical:null}};
export const dynamic='force-dynamic';
const policy:Record<Locale,string[]>={
 en:['Inquiry privacy','We use your contact details and request to assess your needs and communicate with you. This web form does not accept attachments. If supporting documents are needed, we will ask you to send them later in the support email thread. Ask us to agree an NDA before sending confidential materials if necessary. Do not submit passwords, payment-card details or identity documents.','When online intake is enabled, inquiry records are stored with Supabase and only authorized staff can access them. Transactional notifications use Resend. Web inquiry content is not automatically sent to public AI models.','Closed and spam inquiries are scheduled for deletion after 12 months; contractual records may require separate retention agreed for the project. Documents later exchanged by email follow the support mailbox and email-provider retention policies. Contact support@seekapi.ai to request access, correction or deletion.'],
 ja:['問い合わせ情報の取り扱い','連絡先と依頼内容は、ご要望の確認と連絡に利用します。このWebフォームでは添付ファイルを受け付けません。資料が必要な場合は、その後のサポートメールで送付をご案内します。機密資料を送る前に必要に応じてNDAをご相談ください。パスワード、決済カード情報、本人確認書類は送らないでください。','オンライン受付が有効な場合、問い合わせ記録はSupabaseに保存され、許可された担当者のみがアクセスできます。通知メールにはResendを使用します。Web問い合わせ内容を公開AIモデルへ自動送信しません。','終了済み・迷惑問い合わせは12か月後に削除予定です。契約記録は案件ごとに別の保存期間が必要な場合があります。後続メールで交換した資料にはサポートメールボックスとメール提供者の保存方針が適用されます。開示・訂正・削除は support@seekapi.ai へ。'],
 es:['Privacidad de consultas','Usamos sus datos de contacto y solicitud para evaluar sus necesidades y comunicarnos con usted. Este formulario web no acepta archivos adjuntos. Si necesitamos documentos, se los pediremos posteriormente en el hilo de correo de soporte. Si necesita un acuerdo de confidencialidad, solicítelo antes de enviar información sensible. No envíe contraseñas, tarjetas de pago ni documentos de identidad.','Cuando la recepción en línea está habilitada, los registros de consulta se guardan en Supabase y solo el personal autorizado puede acceder. Las notificaciones usan Resend. El contenido del formulario no se envía automáticamente a modelos públicos de IA.','Las consultas cerradas y el spam se programan para eliminación a los 12 meses; los registros contractuales pueden tener otro plazo acordado. Los documentos intercambiados después por correo siguen las políticas del buzón de soporte y del proveedor de correo. Para acceso, corrección o eliminación: support@seekapi.ai.'],
 ar:['خصوصية الاستفسارات','نستخدم بيانات التواصل والطلب لتقييم احتياجاتك والتواصل معك. هذا النموذج لا يقبل المرفقات. إذا احتجنا إلى مستندات فسنطلب إرسالها لاحقاً في محادثة البريد الإلكتروني مع الدعم. اطلب اتفاقية سرية قبل إرسال مواد حساسة عند الحاجة. لا ترسل كلمات المرور أو بيانات بطاقات الدفع أو وثائق الهوية.','عند تفعيل الاستقبال الإلكتروني، تُحفظ سجلات الاستفسار لدى Supabase ولا يصل إليها إلا الموظفون المخولون. تستخدم الإشعارات Resend. لا يُرسل محتوى الاستفسار تلقائياً إلى نماذج ذكاء اصطناعي عامة.','تُجدول الاستفسارات المغلقة والمزعجة للحذف بعد 12 شهراً، وقد تخضع السجلات التعاقدية لمدة أخرى متفق عليها. المستندات التي تُتبادل لاحقاً عبر البريد تخضع لسياسات الاحتفاظ الخاصة بصندوق الدعم ومزود البريد. لطلب الوصول أو التصحيح أو الحذف: support@seekapi.ai.'],
 de:['Datenschutz für Anfragen','Wir verwenden Ihre Kontaktdaten und Anfrage zur Bedarfsprüfung und Kommunikation. Dieses Webformular akzeptiert keine Anhänge. Benötigte Unterlagen fordern wir später im Support-E-Mail-Verlauf an. Vereinbaren Sie bei Bedarf vor dem Versand vertraulicher Unterlagen eine NDA. Übermitteln Sie keine Passwörter, Zahlungskartendaten oder Ausweisdokumente.','Bei aktivierter Online-Annahme werden Anfrage-Datensätze bei Supabase gespeichert und sind nur für befugte Mitarbeiter zugänglich. Benachrichtigungen erfolgen über Resend. Formularinhalte werden nicht automatisch an öffentliche KI-Modelle gesendet.','Geschlossene und Spam-Anfragen werden nach 12 Monaten zur Löschung vorgesehen; für Vertragsunterlagen können gesonderte Fristen gelten. Später per E-Mail ausgetauschte Dokumente unterliegen den Aufbewahrungsregeln des Support-Postfachs und E-Mail-Anbieters. Auskunft, Berichtigung oder Löschung: support@seekapi.ai.'],
 'pt-BR':['Privacidade das consultas','Usamos seus dados de contato e solicitação para avaliar suas necessidades e nos comunicar com você. Este formulário não aceita anexos. Se forem necessários documentos, pediremos o envio posteriormente no e-mail de suporte. Solicite um acordo de confidencialidade antes de enviar material sigiloso, se necessário. Não envie senhas, dados de cartões ou documentos de identidade.','Quando o recebimento on-line está habilitado, os registros ficam no Supabase e somente a equipe autorizada pode acessá-los. As notificações usam Resend. O conteúdo do formulário não é enviado automaticamente a modelos públicos de IA.','Consultas encerradas e spam são programados para exclusão após 12 meses; registros contratuais podem ter prazo específico. Documentos trocados posteriormente por e-mail seguem as políticas de retenção do e-mail de suporte e do provedor. Para acesso, correção ou exclusão: support@seekapi.ai.'],
 ru:['Конфиденциальность запросов','Контактные данные и текст запроса используются для оценки потребностей и связи с вами. Эта веб-форма не принимает вложения. Если понадобятся документы, мы попросим отправить их позже в переписке с поддержкой. При необходимости согласуйте NDA до отправки конфиденциальных материалов. Не отправляйте пароли, данные платёжных карт или удостоверения личности.','При включённом онлайн-приёме записи запросов хранятся в Supabase и доступны только уполномоченному персоналу. Для уведомлений используется Resend. Содержимое формы не отправляется автоматически в публичные модели ИИ.','Закрытые запросы и спам планируются к удалению через 12 месяцев; договорные записи могут иметь отдельный срок хранения. Документы, переданные позже по электронной почте, подчиняются правилам хранения почтового ящика поддержки и почтового провайдера. Доступ, исправление или удаление: support@seekapi.ai.']
};
export default async function Page({searchParams}:{searchParams:Promise<{lang?:string}>}){const params=await searchParams;const locale=locales.includes(params.lang as Locale)?params.lang as Locale:'en';const p=policy[locale];return <PageShell><section className="section"><div className="container" lang={locale} dir={locale==='ar'?'rtl':'ltr'}><h1>{p[0]}</h1>{p.slice(1).map(t=><p key={t}>{t}</p>)}<p>Supabase: {process.env.INQUIRY_STORAGE_REGION_LABEL||'Not configured / online intake not enabled'}</p><p>SeekAPI Technology Limited · <a href="mailto:support@seekapi.ai">support@seekapi.ai</a></p><p>{copy[locale].boundary}</p></div></section></PageShell>;}
