import Link from 'next/link';
import { CTA, Eyebrow, FAQList, FeatureCard, PageShell, SectionTitle, ServiceFaqSchema, type FaqItem } from '@/components/site';
import { pageMetadata } from '@/lib/site';

export const metadata=pageMetadata('China Compliance, Market Entry & Fulfillment','China-side coordination for product compliance, brand protection, market entry, customs documentation, logistics, warehousing and fulfillment.','/china-compliance-logistics');
const faqs:FaqItem[]=[{question:'Can SeekAPI guarantee registration, certification or customs clearance?',answer:'No. SeekAPI can map requirements, coordinate providers and documents, monitor milestones and preserve evidence, but does not guarantee regulatory approval, certification, customs release, tax treatment or transit time.'},{question:'What is needed for an initial route check?',answer:'Product, origin, destination, intended use, sales route, trade direction, expected scale and the current blocker. Do not send sensitive files at the first step.'},{question:'Can logistics, warehousing and returns be handled together?',answer:'Within an agreed scope, SeekAPI can normalize quotes, monitor shipment milestones, preserve inventory evidence and coordinate quarantine, inspection, rework, claims and reverse logistics.'}];

export default function Page(){return <PageShell>
  <ServiceFaqSchema name="China Compliance, Market Entry and Fulfillment Coordination" description="China-side coordination for product pathways, brand protection, customs documents, logistics, warehousing and market entry." path="/china-compliance-logistics" faqs={faqs}/>
  <section className="page-hero"><div className="container"><Eyebrow>For overseas companies</Eyebrow><h1>The work between “we found a supplier” and “the business actually works.”</h1><p>Overseas companies often need more than sourcing. Products may require registration, testing, labels, licensed operators, customs documents, tax records, controlled logistics and local follow-through. SeekAPI maps the required path, coordinates qualified providers and keeps actions, evidence, costs and exceptions visible.</p><div className="button-row"><Link className="button" href="/start?audience=company&intent=compliance">Check a China compliance path</Link><Link className="button button-ghost" href="/start?audience=company&intent=logistics">Plan logistics and warehousing</Link></div></div></section>

  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Two directions · different obligations" title="Start with the direction of trade." body="Product, origin, destination, intended use and sales route determine which requirements and qualified parties may be relevant."/><div className="grid-3"><FeatureCard title="Source in China, sell overseas" body="Coordinate supplier evidence, product and packaging requirements, export readiness, customs documentation, freight, warehousing and destination handoff."/><FeatureCard title="Enter or operate in China" body="Map market-access questions, entity and partner roles, brand and product-registration needs, Chinese labels, import arrangements, tax, data and local fulfillment."/><FeatureCard title="China-side operating support" body="Keep providers, shipments, stock, documents, deadlines, exceptions and responsible people in one operating view."/></div></div></section>

  <section className="section"><div className="container"><SectionTitle eyebrow="Compliance and procedures" title="Compliance starts before the order."/><div className="grid-3"><FeatureCard title="Entity & license verification" body="Verify legal entity, business status, relevant licenses, contracting name, company chop and receiving bank details before relying on a provider."/><FeatureCard title="Product regulatory path" body="Identify product category, use and destination, then map standards, registrations, filings, tests, labels and qualified professionals that may be required."/><FeatureCard title="Brand & intellectual property" body="Coordinate trademark searches and filings, authorization, tooling and drawing ownership, confidentiality and customs IP questions through qualified providers where required."/><FeatureCard title="Contract & authority controls" body="Confirm contracting entity, specifications, acceptance criteria, change approval, delivery terms, liability and dispute path."/><FeatureCard title="Tax, invoice & payment readiness" body="Confirm who sells, exports, imports, invoices and receives payment. Route tax and foreign-exchange questions to qualified professionals."/><FeatureCard title="Renewals & deadlines" body="Track registrations, permits, certificates, tests and contracts whose expiry could interrupt supply or market access."/></div></div></section>

  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Export readiness" title="A chain, not one document."/><div className="grid-3"><FeatureCard title="Product & packaging" body="Control the approved revision, materials, markings, warnings, barcodes, packaging strength and destination-specific requirements before production release."/><FeatureCard title="Testing & certification" body="Compare qualified laboratories, control samples and revisions, and return certificates with their scope and limitations."/><FeatureCard title="Customs documentation" body="Coordinate the exporter, product descriptions, classification inputs, quantities, values, origin, licenses and supporting documents with a qualified customs route."/><FeatureCard title="Controlled goods screening" body="Identify possible export-control, end-use, battery, chemical, magnetic, food, cosmetic, medical or other category-specific questions before transport is booked."/><FeatureCard title="Freight & handoff" body="Compare total landed cost, transit time, Incoterms, surcharges, cutoffs, insurance, customs responsibility and exception handling—not headline freight alone."/><FeatureCard title="Destination-market handoff" body="China-side documents do not prove destination compliance. The buyer or its qualified local provider remains responsible for destination requirements."/></div></div></section>

  <section className="section"><div className="container"><SectionTitle eyebrow="China market entry" title="Market entry is product-specific."/><div className="grid-3"><FeatureCard title="Access & investment check" body="Coordinate a review of whether the proposed activity is open, restricted, prohibited or license-dependent before an entity or partner structure is chosen."/><FeatureCard title="Entity, importer & distributor" body="Define who contracts, imports, holds registrations, invoices, stores inventory, handles complaints and controls the exit path."/><FeatureCard title="Chinese trademark & name" body="Search and file Chinese and Latin-character brand versions early, then keep labels, stores, distributors and authorization documents consistent."/><FeatureCard title="Registration, filing & labels" body="Determine category-specific product and Chinese-label requirements before import or sale, using qualified providers and the responsible authority where required."/><FeatureCard title="Tax, invoicing & settlement" body="Define the transaction chain, invoicing, import and domestic tax questions, cross-border payments and supporting records with qualified advisers."/><FeatureCard title="Data & customer operations" body="Map personal-information handling, customer service, warranties, complaints, returns and recalls before launch."/></div></div></section>

  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Monitored logistics and warehousing" title="Make movement, stock and exceptions visible."/><div className="grid-3"><FeatureCard title="Comparable logistics quotes" body="Normalize route, mode, chargeable weight, Incoterms, base rate, surcharges, customs fees, insurance, storage, free time, validity and exclusions."/><FeatureCard title="Shipment milestones" body="Track booking, pickup, receipt, consolidation, customs status, departure, transshipment, arrival, clearance and final delivery."/><FeatureCard title="Warehouse controls" body="Define inbound checks, SKU and lot identity, quantity, condition, storage rules, access, counts, aging, expiry and outbound authorization."/><FeatureCard title="Inventory visibility" body="Report current, reserved, available, damaged or quarantined stock, aging and movement history in an agreed format."/><FeatureCard title="Exceptions & claims" body="Preserve timestamps, photos, counts, packaging condition, provider records and communication for shortage, damage, delay or insurance claims."/><FeatureCard title="Returns & rework" body="Coordinate return authorization, quarantine, inspection, rework, replacement, disposal and evidence within the agreed role."/></div></div></section>

  <section className="section"><div className="container"><SectionTitle eyebrow="Risk prevention" title="Problems overseas buyers should catch early."/><div className="definition-grid"><div className="definition"><h3>Entity and money</h3><p>A contracting name, company chop or bank account that does not match the approved legal entity.</p></div><div className="definition"><h3>Brand and data</h3><p>Late trademark filing, unclear tooling ownership, or drawings and personal information shared beyond the approved purpose.</p></div><div className="definition"><h3>Product and documents</h3><p>Production before the regulatory path is known, or inconsistent descriptions, classifications, values, quantities and origins.</p></div><div className="definition"><h3>Cargo and inventory</h3><p>Controlled goods booked as ordinary cargo, hidden freight costs, lost lot identity, weak stock records or missing claim evidence.</p></div></div></div></section>

  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Role boundary" title="One accountable coordinator. Qualified providers where required." body="SeekAPI can map requirements, collect facts, prepare checklists, compare providers, coordinate documents and appointments, monitor milestones, preserve evidence and escalate exceptions. Legal opinions, tax filings, audits, certifications, laboratory reports, customs declarations, regulated transport and other licensed work are performed only by the customer or an appropriately qualified provider. SeekAPI does not guarantee regulatory approval, customs release, tax treatment, certification, transit time or legal outcome."/><div className="link-list"><Link className="text-link" href="/trust">Read data and commercial boundaries</Link><Link className="text-link" href="/how-it-works">See the controlled operating path</Link></div></div></section>
  <FAQList eyebrow="Common questions" title="Coordination is not a substitute for a required license." faqs={faqs}/>
  <CTA title="Start with a route check." body="Tell us the product, origin, destination, intended use, sales route and current blocker. Do not send sensitive files before handling and recipients are agreed." primaryLabel="Prepare a non-sensitive request" primaryHref="/start?audience=company&intent=compliance" secondaryLabel="Email support" secondaryHref="mailto:support@seekapi.ai"/>
</PageShell>}
