import { cscCommercialTruth as truth } from '@/lib/csc-commercial-truth';
export const dynamic='force-static';
export async function GET(){return Response.json({
  commercial_truth:truth,versions:truth.versions,contract_updated_at:truth.contract_updated_at,observed_at:new Date().toISOString(),current_sample_url:truth.sample_report,
  provider:'SeekAPI',service_family:'human_execution_china_supply_chain',version:'0.1-preview',status:'manual_review_preview',
  public_api_live:false,intake_enabled:true,intake_mode:'user-reviewed_email',structured_web_submission_live:false,geographic_scope:['China — scope, location and availability reviewed per task'],
  purpose:'China-side procurement desk for overseas buyers and AI agents: manual scope review can lead to accepted supplier contact, RFQ and quote comparison, samples and procurement or export coordination.',
  supported_task_types:[],manual_scope_review_available:true,manual_scope_review_path:'https://seekapi.ai/start?audience=agent',live_human_task_api:false,
  service_path:[{step:'China Supply Check',status:'LIVE_MCP_X402',outcome:'three RFQ-worthy supplier candidates with evidence on success',price:'2.99 USDC on Base'},{step:'supplier contact / RFQ / quote comparison',status:'MANUAL_SCOPE_REVIEW_REQUIRED',price:'quoted after scope review'},{step:'sample / procurement / export coordination',status:'MANUAL_SCOPE_REVIEW_REQUIRED',price:'quoted after scope review'}],
  handoff_requires:['requester_type','requester_identity','organization','objective','task_type','context_summary','allowed_actions','prohibited_actions','recipient_permissions','max_budget','currency','deadline','required_evidence','completion_definition','human_approval_contact'],
  requires_human_approval_for:['RFQ authorization','spending','contracts','production approval','accepting quality deviations'],
  output_states:['NEEDS_INFO','ACCEPTED','HUMAN_REVIEW_REQUIRED','IN_PROGRESS','BLOCKED','APPROVAL_REQUIRED','EVIDENCE_READY','COMPLETED','DECLINED'],
  data_policy_url:'https://seekapi.ai/trust#data-ip',handoff_spec_url:'https://seekapi.ai/for-agents#handoff-spec',start_url:'https://seekapi.ai/start?audience=agent',commercial_language_entry_urls:{ja:'https://seekapi.ai/ja',es:'https://seekapi.ai/es',ar:'https://seekapi.ai/ar',de:'https://seekapi.ai/de','pt-BR':'https://seekapi.ai/pt-br',ru:'https://seekapi.ai/ru'},evidence_return_spec_url:'https://seekapi.ai/for-agents#evidence-return',compliance_logistics_url:'https://seekapi.ai/china-compliance-logistics',manual_scope_contact:'mailto:support@seekapi.ai',
  product_data_discovery_url:'https://seekapi.ai/apis#product-search',
  product_data_mcp:{live:true,endpoint:'https://api.seekapi.ai/mcp',transport:'streamable-http',csc_public_paid_on:true,price_usdc:'2.99',stripe_checkout:'PUBLIC_OFF',free_tools:['discover_china_supply_check_v0','prepare_china_supply_check_v0'],authenticated_order_read_tools:['status_china_supply_check_v0','result_china_supply_check_v0'],paid_effect_tools:['purchase_china_supply_check_v0','run_china_supply_check_v0'],status_result_access:'independent signed-wallet authentication bound to the settled order',image_input:{no_value_prepare:true,accepted_mime:['image/png'],public_paid_execution:false,purchase_state:'PUBLIC_OFF'}},
  official_mcp_registry:{package:'io.github.kiddhu/seekapi',registry_package_version:truth.versions.registry_package_version,publication_status:'CHECK_OFFICIAL_LATEST',url:'https://registry.modelcontextprotocol.io/v0.1/servers/io.github.kiddhu%2Fseekapi/versions/latest',version_note:'Build package version; use the official latest endpoint for publication status'},
  integrations:{task_api:'planned_not_live',mcp:'planned_not_live',webmcp:'planned_not_live'},updated_at:'2026-10-08',
  notes:['SeekAPI-defined preview manifest, not an industry standard.','The task_api, mcp and webmcp integration status in this manifest applies only to human tasks; human-task API execution is not live. Manual scope review is requestable, but no task is accepted until separately agreed.','Product-data MCP (China Supply Check) discovery and prepare are live at the product_data_mcp endpoint; its paid text/model check costs 2.99 USDC via x402 with public credit-card checkout OFF. Bounded PNG preparation is no-value only: public image purchase is OFF; free image preparation is available.','The website can prepare a user-reviewed email request; it does not transmit data itself. No public task API, automatic acceptance or universal live coverage is claimed.']
});}