import Link from 'next/link';
import { CTA, Eyebrow, FeatureCard, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';
export const metadata=pageMetadata('China Desk','Ongoing, scope-based China-side support for recurring supplier and production work.','/china-desk');
export default function Page(){return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>Ongoing company service</Eyebrow><h1>A China-side desk without building the whole team first.</h1><p>For companies with recurring supplier, sample, quality, production or delivery work, a China Desk turns separate requests into one managed operating relationship.</p><div className="button-row"><Link className="button" href="/start?audience=company&intent=china-desk">Request a China Desk plan</Link><Link className="button button-ghost" href="/china-supply-chain">Start with a project</Link></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="How it starts" title="Prove the working relationship on one issue."/><div className="grid-3"><FeatureCard index="01" title="Project Sprint" body="One defined China-side assignment with an agreed fee, role, output and stopping point."/><FeatureCard index="02" title="Review the pattern" body="Confirm whether work is recurring, which tasks repeat, and where decisions still belong to your team."/><FeatureCard index="03" title="China Desk" body="Move recurring work into a monthly, scope-based operating plan."/></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Scope dimensions" title="Capacity is defined around the work." body="A Desk plan can define active workstreams, supplier count, task classes, response windows, review cadence, evidence and escalation contacts. Actual scope and service levels are agreed before work begins."/><div className="grid-3"><FeatureCard title="Named responsibility" body="A clear owner, current status, next action and escalation route for accepted work."/><FeatureCard title="Operating rhythm" body="Regular status and review around supplier commitments, samples, issues and milestones."/><FeatureCard title="Right-sized structure" body="When stable workload justifies an internal team, that may become the better long-term choice."/></div></div></section>
  <CTA title="Turn recurring China-side work into one accountable desk." body="Begin with a non-sensitive description of the work. The preview form does not submit data." primaryLabel="Request a Desk plan" primaryHref="/start?audience=company&intent=china-desk" secondaryLabel="Trust and roles" secondaryHref="/trust"/>
</PageShell>}
