import Link from 'next/link';
import { CTA, Eyebrow, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';
export const metadata=pageMetadata('How SeekAPI Works','Prepare a product brief, inspect source-linked listing evidence and understand the separate planned RFQ step. China Supply Check costs 2.99 USDC per accepted order; Live RFQ Compare remains planned.','/how-it-works');
const steps=[
 ['01','One issue','A concrete problem, component or blocked task.','Clarify outcome and timing.','Confirm the problem is worth solving.','A bounded starting point.','Stop if there is no decision value.'],
 ['02','Fit and scope','Non-sensitive context and commercial objective.','Return fit, no-go or missing information.','Approve the proposed scope.','Defined work package.','Stop if SeekAPI is not the right role.'],
 ['03','Inputs and rights','Files, revisions, owners and sharing rights.','Separate internal review from external authorization.','Approve recipients and purpose.','Controlled input set.','Stop if rights are unclear.'],
 ['04','Supplier, RFQ or recovery','Approved action and named parties.','Contact, source, compare or recover facts.','Resolve commercial choices.','Responses and explicit unknowns.','Stop at unapproved commitment or spend.'],
 ['05','Sample, NPI and quality','Acceptance criteria and current revision.','Track evidence, deviations and issue closure.','Approve or reject the next state.','Decision-ready sample or quality record.','Stop when evidence is insufficient.'],
 ['06','Production and delivery','Approved order context and milestones.','Coordinate status, packaging and readiness.','Make qualified product and shipment decisions.','Current status and exceptions.','Stop at role, compliance or authority boundary.'],
 ['07','Repeat or Desk','Evidence from completed work.','Review recurring task pattern.','Choose project close, repeat or monthly Desk.','Clear operating model.','Stop if in-house becomes the better structure.'],
];
export default function Page(){return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>Operating model</Eyebrow><h1>From a product brief to an evidence-screened sourcing decision.</h1><p>Start with the product or model, quantity and must-have specifications. Free Product Brief preparation requires an MCP-capable client. China Supply Check costs 2.99 USDC per accepted order; Live RFQ Compare remains planned.</p></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="China Supply Check" title="Three steps, with separate order and payment confirmation."/><div className="process-grid"><article className="process-step"><span>01</span><div><h3>Prepare the exact brief</h3><p>An MCP-capable client can prepare a free draft with product/model, quantity and unit, hard specifications and substitution permission. Preparation neither buys a check nor contacts suppliers.</p></div></article><article className="process-step"><span>02</span><div><h3>Inspect the screening contract</h3><p>On a successful paid check, three distinct documented shop candidates include source links, observation time, listing-price basis, MOQ/spec fit, exclusions and UNKNOWNs. Certification and company or production-versus-trade identity evidence is reported per candidate when available; a published price is dated supplier evidence with quantity conditions, and a confirmed reply is a separate step.</p></div></article><article className="process-step"><span>03</span><div><h3>Review the evidence and next question</h3><p>Read the production acceptance summary, or the separately archived historical V4 example preserved for provenance. A future Live RFQ Compare would use your edited and confirmed RFQ, up to three selected suppliers, separate payment and authorization, and one human outreach round in a 72-hour response window. Replies are not guaranteed; this step is closed.</p></div></article></div><div className="link-list"><Link className="text-link" href="/china-supply-check">Product scope</Link><Link className="text-link" href="/china-supply-check/sample">Sample summary</Link><Link className="text-link" href="/for-agents#china-supply-check-mcp">Connect a free MCP client</Link></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Company path" title="Seven steps from one issue to an operating relationship."/><div className="process-grid">{steps.map(([n,title,input,action,decision,output,stop])=><article className="process-step" key={n}><span>{n}</span><div><h3>{title}</h3><div className="facts"><div className="fact"><strong>Input</strong><span>{input}</span></div><div className="fact"><strong>SeekAPI action</strong><span>{action}</span></div><div className="fact"><strong>Buyer decision</strong><span>{decision}</span></div><div className="fact"><strong>Output</strong><span>{output}</span></div><div className="fact"><strong>Stop condition</strong><span>{stop}</span></div></div></div></article>)}</div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Agent path" title="The same control model, with a structured return." body="An Agent completes machine work, identifies a human trigger, supplies bounded permissions and evidence requirements, then resumes from a structured human result. Human review can return NEEDS_INFO, DECLINED or APPROVAL_REQUIRED without pretending a task was accepted."/></div></section>
  <CTA title="Start from one real task." body="For broader Desk support, prepare a non-sensitive email locally and choose whether to send it. The website does not submit or accept a task." primaryHref="/start" secondaryLabel="Trust and permissions" secondaryHref="/trust"/>
</PageShell>}
