import Link from 'next/link';
import { Eyebrow, PageShell } from '@/components/site';
import { pageMetadata } from '@/lib/site';

export const metadata = pageMetadata('Privacy Notice', 'How SeekAPI Technology Limited handles product briefs, support messages, service orders and technical request data.', '/privacy');

export default function PrivacyPage() { return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>Privacy notice</Eyebrow><h1>What we need to help you, and what happens to it.</h1><p>SeekAPI Technology Limited operates seekapi.ai and the public SeekAPI MCP endpoint. This notice describes the data handled when you visit, prepare a brief, contact support or place an accepted service order. For privacy questions or a request to access or correct your personal data, email <a className="text-link" href="mailto:support@seekapi.ai">support@seekapi.ai</a>.</p><p>Version 1 · 30 September 2026</p></div></section>
  <section className="section"><div className="container"><h2>What you provide</h2><p>A free China Supply Check brief can include a product or model, quantity, unit, required specifications, reference and substitution choice. A support message may include your name, contact address, question and report or order reference. If SeekAPI accepts a paid order, its order and payment confirmation may include a transaction reference and information needed to deliver the result. Do not put passwords, wallet private keys, payment proof secrets or sensitive drawings into a brief or support message before a handling scope is agreed.</p><p>Providing a brief or support details is voluntary. Without the information needed for a requested service, we may be unable to prepare the brief, respond or accept an order.</p></div></section>
  <section className="section section-dark"><div className="container"><h2>How we use the information</h2><p>We use relevant information to prepare and confirm a brief, answer support requests, confirm an accepted order and its payment, perform and deliver a purchased check, keep the result available to its authorized buyer, protect the service from misuse and meet applicable recordkeeping obligations. A free brief is not an accepted order or payment instruction. China Supply Check does not include supplier outreach; a separate service needs its own authorization.</p></div></section>
  <section className="section"><div className="container"><h2>Who may handle it</h2><p>Website, security, email, API, research and payment service providers may handle the parts needed for their roles. Product specifications needed for listing research may be sent to a data or search provider; do not include personal or confidential material in a free brief. A supported payment route and its provider are identified during the order process before payment. SeekAPI does not send a China Supply Check brief to a supplier as an RFQ without separate authorization. Providers may process information outside Hong Kong.</p></div></section>
  <section className="section section-dark"><div className="container"><h2>Technical data and retention</h2><p>Requests to the site and API carry technical information such as IP address, user agent, time and requested path. Hosting and security services use this information to deliver and protect the service and may use essential cookies or similar identifiers. Service, support, order and security records are kept only as long as needed for their stated purposes and applicable obligations, then deleted or de-identified where practicable. Ask us about the handling of a particular record or a deletion request; some payment or legal records may need to be retained.</p></div></section>
  <section className="section"><div className="container"><h2>Your questions and requests</h2><p>Contact <a className="text-link" href="mailto:support@seekapi.ai">support@seekapi.ai</a> to ask what personal data we hold, request access or correction, or raise a privacy concern. We may need to verify that the request concerns your data. Our contact address is Room P11, Flat 2C, 2/F, Hung To Ctr., 94–96 How Ming St., Kwun Tong, Kowloon, Hong Kong. We will update this notice if the actual handling or a supported payment route changes materially.</p><p><Link className="text-link" href="/terms">Read the service terms</Link> · <Link className="text-link" href="/support">Contact support</Link></p></div></section>
</PageShell>; }
