import { Eyebrow, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';

export const metadata = pageMetadata(
  'Privacy Notice | SeekAPI',
  'How SeekAPI Technology Limited handles product requirements, support correspondence, technical logs and transaction information.',
  '/privacy',
);

export default function Page() { return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>Privacy Notice · Effective September 30, 2026</Eyebrow><h1>Use only the information needed to complete the sourcing task.</h1><p>SeekAPI Technology Limited operates seekapi.ai and related SeekAPI services. Contact <a className="text-link" href="mailto:support@seekapi.ai">support@seekapi.ai</a> about privacy requests.</p></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Information we process" title="Product requirements, service records and necessary technical data."/><div className="definition-grid"><div className="definition"><h3>Product and order information</h3><p>Product names, models or part numbers, quantities, units, specifications, references, Product Briefs, order status and sourcing results that you or an authorized Agent provide.</p></div><div className="definition"><h3>Support information</h3><p>Email address, correspondence, order or report references and information you choose to provide when asking for support.</p></div><div className="definition"><h3>Technical and security data</h3><p>IP address, client or browser type, request time, request identifiers, service logs, error records and security events reasonably necessary to operate and protect the service.</p></div><div className="definition"><h3>Payment records</h3><p>Order, entitlement, settlement and accounting records needed to process or reconcile paid services. SeekAPI does not ask you to provide wallet private keys.</p></div></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Why we use it" title="Provide the service, support the customer and protect the system." body="Information may be used to prepare and complete sourcing work, maintain order and payment records, respond to support, secure the service, diagnose failures, meet legal obligations and evaluate service reliability. Automated and AI-assisted systems may process product information as part of providing or improving the service."/><p>SeekAPI does not sell personal information and does not use customer Product Briefs for third-party targeted advertising.</p></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Service providers and transfers" title="Only as needed to operate the service." body="SeekAPI may use infrastructure, hosting, security, communications, payment, data and AI providers. Those providers may process information in Hong Kong or other jurisdictions where they operate. Access is limited to what is reasonably required for the relevant service. Information may also be disclosed where required by applicable law."/></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Retention and security" title="Keep records only as long as reasonably necessary." body="Operational information is retained for the period reasonably necessary to provide the service, support customers, maintain security and resolve disputes. Transaction, tax, accounting and other business records are retained for the period required by applicable law. Aggregated or de-identified information may be retained longer when it no longer reasonably identifies a person."/><p>SeekAPI uses reasonable technical and organizational measures designed to protect information against unauthorized access, disclosure, alteration or loss. No Internet service can guarantee absolute security.</p></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Your requests" title="Access, correction and deletion requests." body="Contact support@seekapi.ai to request access to, correction of or deletion of personal information associated with you, subject to identity verification, applicable law and legitimate retention requirements."/><p>Please do not submit passwords, wallet private keys, bearer payment proofs, unnecessary identity documents or unrelated sensitive personal information.</p></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Operator" title="SeekAPI Technology Limited" body="Room P11, Flat 2C, 2/F, Hung To Ctr., 94–96 How Ming St., Kwun Tong, Kowloon, Hong Kong · support@seekapi.ai"/></div></section>
</PageShell>; }
