import Link from 'next/link';
import { CTA, Eyebrow, FeatureCard, Footer, Header, MetricCard, Pill, SectionTitle, SplitPanel } from '@/components/site';
import { pageMetadata } from '@/lib/site';

export const metadata=pageMetadata('SeekAPI — APIs and Human Execution in China','SeekAPI provides developer APIs, China-side sourcing, compliance, logistics and bounded human handoffs for AI Agents.','/');

export default function HomePage() {
  return <><Header /><main id="main-content">
    <section className="hero"><div className="container hero-grid">
      <div><Eyebrow>APIs · company services · Agent handoffs</Eyebrow><h1>Software can go far. Reality still needs people.</h1><p className="lead">SeekAPI is an external China-side desk for sourcing, supplier coordination, compliance pathways, logistics and fulfillment. For AI Agents, we define bounded human handoffs for approved China-side work. Developers can enter the existing API product separately.</p><div className="button-row"><Link className="button" href="/china-supply-chain">For Companies</Link><Link className="button button-ghost" href="/for-agents">For Agents</Link><Link className="button button-ghost" href="/apis">Explore APIs</Link></div><p className="hero-note">Start with one non-sensitive issue. This preview does not submit tasks or payments.</p></div>
      <div className="hero-visual" aria-label="Illustrative workflow connecting software planning with scoped human execution in China"><div className="visual-card dark one"><span className="card-label">Illustrative human workflow</span><div className="visual-big">China-side work with an explicit scope.</div><div className="execution-list"><div className="execution-row"><span>Supplier communication</span><span className="status">Scoped</span></div><div className="execution-row"><span>Physical verification</span><span className="status">Evidence</span></div><div className="execution-row"><span>Samples / quality / delivery</span><span className="status">Reviewed</span></div></div></div><div className="visual-card two"><span className="card-label">Illustrative Agent handoff</span><div className="mini-code">task_type: AH01{`\n`}allowed_actions: [contact]{`\n`}prohibited_actions: [pay, approve]{`\n`}return: [evidence, status]</div></div><div className="visual-card three"><span className="card-label">One brand · three doors</span><div className="tag-list"><Pill>Companies</Pill><Pill>Agents</Pill><Pill>APIs</Pill></div></div></div>
    </div></section>
    <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Why SeekAPI" title="Finding a supplier is only one step." body="Time zones, language, revisions and unresolved supplier questions can make China-side work difficult to coordinate." /><div className="grid-3"><FeatureCard index="01" title="Machine capability" body="Use the existing developer documentation, account and dashboard routes for machine access." /><FeatureCard index="02" title="China Supply Chain Desk" body="External China-side support for sourcing, supplier communication, samples, quality and delivery coordination." /><FeatureCard index="03" title="Human execution for Agents" body="Define approved real-world work and the evidence required before a human handoff is accepted." /></div></div></section>
    <section className="section"><div className="container"><SectionTitle eyebrow="For Companies" title="Your China supply chain, locally managed." body="Use SeekAPI before your workload justifies a full China team — or as an overflow, second-source and exception-management layer when you already have one." /><div className="grid-3"><FeatureCard title="Sourcing & RFQ" body="Turn requirements into comparable supplier options and explicit unknowns." items={["Supplier discovery","RFQ execution","Quote normalization"]}/><FeatureCard title="Samples & NPI" body="Keep versions, questions and approvals from drifting between sample and production." items={["Revision control","Issue closure","Production readiness"]}/><FeatureCard title="Quality & production" body="Make milestones and exceptions observable before they become surprises." items={["Inspection coordination","Production follow-up","Issue recovery"]}/><FeatureCard title="Compliance & market entry" body="Coordinate China-side registrations, product pathways, brand protection, documentation and qualified providers." items={["Entity and license checks","Trademark coordination","Product pathway mapping"]}/><FeatureCard title="Logistics & warehousing" body="Compare total logistics cost, monitor shipment milestones and keep warehouse stock, lots and exceptions visible." items={["Comparable quotes","Shipment monitoring","Inventory evidence"]}/><FeatureCard title="Delivery & reverse logistics" body="Coordinate readiness, exceptions, claims, returns and rework within an agreed responsibility boundary." items={["Delivery readiness","Claim evidence","Returns and rework"]}/></div><div className="button-row" style={{marginTop:26}}><Link className="button" href="/china-supply-chain">Explore the China Desk</Link><Link className="button button-ghost" href="/china-compliance-logistics">Compliance & logistics</Link><Link className="button button-ghost" href="/china-desk">Ongoing China Desk</Link></div></div></section>
    <section className="section section-tight"><div className="container"><SplitPanel left={<><Eyebrow>For Agents</Eyebrow><h3>Give your agent hands in China.</h3><p>Your agent keeps the context. SeekAPI handles the approved local human work — calls, supplier follow-through, verification, inspection coordination and exceptions — and returns evidence in a structured form.</p><div className="button-row" style={{marginTop:22}}><Link className="button" href="/for-agents">Human Execution Layer</Link></div></>} right={<><Eyebrow>Bounded by design</Eyebrow><h3>Human work without losing control.</h3><p>Every accepted task can define allowed actions, forbidden actions, spend limits, recipients, files, deadlines and required evidence. “Done” is not the output; evidence and unresolved items are.</p><div className="tag-list"><Pill>Structured handoff</Pill><Pill>Bounded authority</Pill><Pill>Evidence return</Pill></div></>} /></div></section>
    <section className="section section-dark"><div className="container"><SectionTitle eyebrow="A practical trust model" title="We separate claims from evidence." body="SeekAPI V0.1 does not pretend that every future capability is already live. Public claims are evidence-gated, and service roles are made explicit before work or payment begins." /><div className="metric-grid"><MetricCard label="First step" value="One issue" detail="Start narrow. No full CAD dump required." /><MetricCard label="Data control" value="You approve" detail="Internal review does not equal external RFQ authorization." /><MetricCard label="Commercial role" value="Explicit" detail="Service provider vs seller is stated before the transaction." /></div></div></section>
    <section className="section"><div className="container"><SectionTitle eyebrow="Evidence before claims" title="See how decisions are made." body="The proof area separates verified work from self-funded demonstrations, public analysis and illustrative workflows."/><div className="button-row"><Link className="button" href="/proof">Explore proof and examples</Link><Link className="button button-ghost" href="/trust">Read the trust model</Link></div></div></section>
    <CTA eyebrow="Start small" title="One problem is enough to begin." body="Prepare a non-sensitive company issue or Agent handoff. The current preview validates a draft locally and sends nothing." secondaryLabel="See how it works" secondaryHref="/how-it-works" />
  </main><Footer /></>;
}
