import Link from 'next/link';
import { CTA, Eyebrow, FeatureCard, Footer, Header, MetricCard, Pill, SectionTitle, SplitPanel } from '@/components/site';

export default function HomePage() {
  return <><Header /><main>
    <section className="hero"><div className="container hero-grid">
      <div><Eyebrow>Machine capability + human execution</Eyebrow><h1>Software can go far. Reality still needs people.</h1><p className="lead">SeekAPI gives companies and AI agents a reliable China-side execution layer — from APIs and supplier research to real human communication, verification, samples, quality and follow-through.</p><div className="button-row"><Link className="button" href="/china-supply-chain">For Companies</Link><Link className="button button-ghost" href="/for-agents">For Agents</Link><Link className="button button-ghost" href="/apis">Explore APIs</Link></div><p className="hero-note">Start with one issue. We do not ask for confidential drawings before the right data path is agreed.</p></div>
      <div className="hero-visual" aria-label="SeekAPI connects software planning with human execution in China"><div className="visual-card dark one"><span className="card-label">Human execution layer</span><div className="visual-big">China-side work that actually moves.</div><div className="execution-list"><div className="execution-row"><span>Supplier communication</span><span className="status">Accountable</span></div><div className="execution-row"><span>Physical verification</span><span className="status">Evidence</span></div><div className="execution-row"><span>Samples / quality / delivery</span><span className="status">Tracked</span></div></div></div><div className="visual-card two"><span className="card-label">Agent handoff</span><div className="mini-code">task_type: supplier_contact{`\n`}allowed: [call, verify]{`\n`}forbidden: [pay, approve]{`\n`}return: [evidence, status]</div></div><div className="visual-card three"><span className="card-label">One brand · three doors</span><div className="tag-list"><Pill>Companies</Pill><Pill>Agents</Pill><Pill>APIs</Pill></div></div></div>
    </div></section>
    <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Why SeekAPI" title="China is easy to buy from. Hard to manage well." body="Most teams do not fail because suppliers are impossible to find. They fail because reality becomes fragmented across time zones, languages, versions, promises and physical-world exceptions." /><div className="grid-3"><FeatureCard index="01" title="Machine capability" body="Search, normalize, compare, route and call structured external capabilities when software is enough." /><FeatureCard index="02" title="China Supply Chain Desk" body="An external China-side operating team for sourcing, supplier communication, samples, quality and delivery coordination." /><FeatureCard index="03" title="Human execution for agents" body="When an agent reaches the edge of software, hand off approved real-world work and get structured evidence back." /></div></div></section>
    <section className="section"><div className="container"><SectionTitle eyebrow="For Companies" title="Your China supply chain, locally managed." body="Use SeekAPI before your workload justifies a full China team — or as an overflow, second-source and exception-management layer when you already have one." /><div className="grid-3"><FeatureCard title="Sourcing & RFQ" body="Turn requirements into comparable supplier options and explicit unknowns." items={["Supplier discovery","RFQ execution","Quote normalization"]}/><FeatureCard title="Samples & NPI" body="Keep versions, questions and approvals from drifting between sample and production." items={["Revision control","Issue closure","Production readiness"]}/><FeatureCard title="Quality & delivery" body="Make milestones and exceptions observable before they become surprises." items={["Inspection coordination","Production follow-up","Delivery readiness"]}/></div><div className="button-row" style={{marginTop:26}}><Link className="button" href="/china-supply-chain">Explore the China Desk</Link><Link className="button button-ghost" href="/china-desk">Ongoing China Desk</Link></div></div></section>
    <section className="section section-tight"><div className="container"><SplitPanel left={<><Eyebrow>For Agents</Eyebrow><h3>Give your agent hands in China.</h3><p>Your agent keeps the context. SeekAPI handles the approved local human work — calls, supplier follow-through, verification, inspection coordination and exceptions — and returns evidence in a structured form.</p><div className="button-row" style={{marginTop:22}}><Link className="button" href="/for-agents">Human Execution Layer</Link></div></>} right={<><Eyebrow>Bounded by design</Eyebrow><h3>Human work without losing control.</h3><p>Every accepted task can define allowed actions, forbidden actions, spend limits, recipients, files, deadlines and required evidence. “Done” is not the output; evidence and unresolved items are.</p><div className="tag-list"><Pill>Structured handoff</Pill><Pill>Bounded authority</Pill><Pill>Evidence return</Pill></div></>} /></div></section>
    <section className="section section-dark"><div className="container"><SectionTitle eyebrow="A practical trust model" title="We separate claims from evidence." body="SeekAPI V0.1 does not pretend that every future capability is already live. Public claims are evidence-gated, and service roles are made explicit before work or payment begins." /><div className="metric-grid"><MetricCard label="First step" value="One issue" detail="Start narrow. No full CAD dump required." /><MetricCard label="Data control" value="You approve" detail="Internal review does not equal external RFQ authorization." /><MetricCard label="Commercial role" value="Explicit" detail="Service provider vs seller is stated before the transaction." /></div></div></section>
    <CTA eyebrow="Start small" title="One problem is enough to begin." body="Tell us what is stuck, what you need to source, or what your agent could not finish safely. We will first decide whether SeekAPI is the right China-side route." secondaryLabel="See how it works" secondaryHref="/how-it-works" />
  </main><Footer /></>;
}
