'use client';
import { useEffect,useState,type FormEvent } from 'react';
import Link from 'next/link';
import { states,type Inquiry } from '@/lib/inquiries/core';
const labels:Record<string,string>={name:'联系人',email:'邮箱',country:'国家 / 地区',message:'需求和预期结果',locale:'提交语言',audience:'客户类型',services:'服务需求',compliance:'合规确认',source:'来源页面',company:'公司 / 项目',website:'网站',role:'职位',preferred_contact:'首选联系方式',wechat:'微信',whatsapp:'WhatsApp',phone:'电话',telegram:'Telegram',preferred_language:'首选语言',timezone:'时区',product:'产品 / 规格 / 参考链接',quantity:'数量 / 单位',budget:'预算 / 币种',deadline:'交期',destination:'交付地点',suppliers:'供应商 / 现有问题',certification:'标准 / 认证 / 文件',logistics:'物流 / 仓储需求',nda:'保密要求',allowed_actions:'允许的动作',prohibited_actions:'禁止的动作',required_evidence:'证据 / 完成标准',approval_contact:'人工审批联系人',task_type:'任务类别'};
const names=['新询盘','评估中','待补资料','已报价','处理中','已关闭','垃圾询盘'];
type Row={id:string;reference:string;payload:Inquiry;status:string;owner:string;created_at:string;deletion_requested_at:string|null};
type Detail={inquiry:Row;events:{note:string;created_at:string}[];mail:{kind:string;state:string;attempts:number}[]};
export function InquiryAdmin({id}:{id?:string}){
 const [login,setLogin]=useState(false);const [ready,setReady]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(true);const [rows,setRows]=useState<Row[]>([]);const [detail,setDetail]=useState<Detail|null>(null);const [query,setQuery]=useState('');const [page,setPage]=useState(0);
 async function call(path:string,init?:RequestInit){const r=await fetch(path,init);if(r.status===401){setLogin(true);throw new Error('请登录工作人员账号');}if(!r.ok)throw new Error(r.status===403?'此账号没有访问权限':'操作失败，请稍后重试。');return r.json();}
 async function load(){setBusy(true);try{const data=await call(id?'/api/admin/inquiries/'+id:'/api/admin/inquiries?'+query+'&page='+page);if(id)setDetail(data);else setRows(data);setLogin(false);setReady(true);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[id,query,page]);
 async function signIn(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await call('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:f.get('email'),password:f.get('password')})});setLogin(false);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function update(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await call('/api/admin/inquiries/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(){if(!window.confirm('申请删除这条询盘记录？后台会停止后续通知并安排清理；清理完成后不可恢复。'))return;try{await call('/api/admin/inquiries/'+id,{method:'DELETE'});await load();}catch(e){setError((e as Error).message);}}
 return <><header className="admin-header"><Link href="/admin/inquiries">SeekAPI · 询盘管理</Link><a href="/">查看官网</a>{ready&&!login?<button onClick={async()=>{await call('/api/admin/session',{method:'DELETE'});setRows([]);setDetail(null);setReady(false);setLogin(true);}}>退出登录</button>:null}</header>
 {error?<p role="alert">{error}</p>:null}{busy?<p role="status">正在处理…</p>:null}
 {!ready&&!login?<p role="status">{busy?'正在验证访问权限…':'后台暂不可用，请稍后重试。'}</p>:login?<form className="form-card" onSubmit={signIn}><h1>工作人员登录</h1><p>仅已授权账号可访问。此处使用独立后台账号，不是邮箱密码。</p><div className="field"><label htmlFor="admin-email">邮箱</label><input id="admin-email" name="email" type="email" autoComplete="username" required/></div><div className="field"><label htmlFor="admin-password">后台密码</label><input id="admin-password" name="password" type="password" autoComplete="current-password" required/></div><button className="button" disabled={busy}>登录</button></form>:id&&detail?<>
 <h1>{detail.inquiry.reference}</h1><p>{detail.inquiry.created_at} · {names[states.indexOf(detail.inquiry.status as typeof states[number])]}</p>
 {detail.inquiry.deletion_requested_at?<p role="status">已申请删除，等待后台清理文件和记录。</p>:null}
 <div className="button-row"><a className="button" href={'mailto:'+detail.inquiry.payload.email+'?subject='+encodeURIComponent('Re: SeekAPI '+detail.inquiry.reference)}>通过邮件回复客户</a><a href={'/api/admin/inquiries/'+id+'?export=1'}>导出完整记录</a><button onClick={remove}>申请删除</button></div>
 <section className="form-card"><h2>客户需求</h2><dl>{Object.entries(detail.inquiry.payload).filter(([k])=>!['details','consent'].includes(k)).map(([k,v])=><div key={k}><dt>{labels[k]||k}</dt><dd>{Array.isArray(v)?v.join(', '):String(v)}</dd></div>)}</dl><h3>补充资料</h3><dl>{Object.entries(detail.inquiry.payload.details).filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{labels[k]||k}</dt><dd>{v}</dd></div>)}</dl></section>
 <section className="form-card"><h2>支持资料</h2><p>本版本网页不接收附件。如需文件、图片或PDF，请通过与客户的后续邮件往来收取和处理。</p></section>
 <section className="form-card"><h2>通知状态</h2>{detail.mail.map(m=><p key={m.kind}>{m.kind==='staff'?'内部通知':'客户回执'}：{m.state} · 尝试次数 {m.attempts}</p>)}<p>provider_accepted 表示邮件服务已接收，不等于已投递到收件箱。邮件往来保留在 support 邮箱。</p></section>
 <form className="form-card" onSubmit={update}><h2>跟进记录</h2><div className="field"><label htmlFor="status">进度</label><select id="status" name="status" defaultValue={detail.inquiry.status}>{states.map((s,i)=><option key={s} value={s}>{names[i]}</option>)}</select></div><div className="field"><label htmlFor="owner">负责人</label><input id="owner" name="owner" maxLength={150} defaultValue={detail.inquiry.owner}/></div><div className="field"><label htmlFor="note">内部备注</label><textarea id="note" name="note" maxLength={5000}/></div><button className="button" disabled={busy}>保存跟进</button></form>
 <section className="form-card"><h2>历史记录</h2>{detail.events.map((e,i)=><article key={i}><small>{e.created_at}</small><p className="preserve-lines">{e.note}</p></article>)}</section>
 </>:<><h1>客户询盘</h1><form className="admin-filters" onSubmit={e=>{e.preventDefault();setPage(0);setQuery(new URLSearchParams(new FormData(e.currentTarget) as never).toString());}}><label>客户 / 公司 / 编号<input name="q"/></label><label>状态<select name="status"><option value="">全部</option>{states.map((s,i)=><option key={s} value={s}>{names[i]}</option>)}</select></label><label>国家<input name="country"/></label><label>语言<select name="language"><option value="">全部</option>{['en','ja','es','ar','de','pt-BR','ru'].map(l=><option key={l}>{l}</option>)}</select></label><label>服务<input name="service"/></label><label>起始日期<input type="date" name="from"/></label><label>结束日期<input type="date" name="to"/></label><button className="button">筛选</button></form>
 <div className="admin-list">{rows.map(r=><Link className="form-card" key={r.id} href={'/admin/inquiries/'+r.id}><strong>{r.reference} · {r.payload.name}</strong><p>{r.payload.details.company} · {r.payload.country} · {r.payload.locale}</p><p>{r.payload.message.slice(0,180)}</p><small>{names[states.indexOf(r.status as typeof states[number])]} · {r.created_at}</small></Link>)}</div>{!busy&&!rows.length?<p>没有匹配的询盘。</p>:null}<div className="button-row"><button disabled={page===0} onClick={()=>setPage(page-1)}>上一页</button><span>第 {page+1} 页</span><button disabled={rows.length<30} onClick={()=>setPage(page+1)}>下一页</button></div></>}
 </>;
}
