import Link from 'next/link';
import { copy as inquiryCopy } from '@/lib/inquiries/translations';
import { Suspense } from 'react';
import { CTA, Eyebrow, FAQList, FeatureCard, PageShell, SectionTitle, ServiceFaqSchema } from './site';
import { LocalizedStartForm } from './localized-start-form';
import { localizedCopy, pagePath, russianCopy, type CommercialLocale, type CommercialPage } from '@/lib/localized-content';

export function CommercialLocalizedPage({locale,page}:{locale:CommercialLocale;page:CommercialPage}){
  const ui=localizedCopy[locale];const copy=ui.pages[page];const start=pagePath(locale,'start');
  const faqs=copy.faq?.map(item=>({question:item.title,answer:item.body}))||[];
  return <PageShell locale={locale}>
    {faqs.length?<ServiceFaqSchema name={copy.title} description={copy.description} path={pagePath(locale,page)} faqs={faqs} locale={locale}/>:null}
    <section className={page==='home'?'hero localized-hero':'page-hero'}><div className="container"><Eyebrow>{copy.eyebrow}</Eyebrow><h1>{copy.heading}</h1><p className="lead">{page==='start'&&process.env.NEXT_PUBLIC_INQUIRIES_ENABLED==='1'?inquiryCopy[locale==='pt-br'?'pt-BR':locale].intro:copy.lead}</p>{page!=='start'?<div className="button-row"><Link className="button" href={start}>{ui.start}</Link>{page==='home'?<><Link className="button button-ghost" href={pagePath(locale,'china-supply-chain')}>{ui.nav['china-supply-chain']}</Link><a className="button button-ghost" href="/apis" hrefLang="en">API · English</a></>:null}</div>:null}</div></section>
    {page==='start'?<section className="section section-tight"><div className="container"><Suspense fallback={<p>…</p>}><LocalizedStartForm copy={ui.form} locale={locale==='pt-br'?'pt-BR':locale}/></Suspense></div></section>:copy.sections.map((section,index)=><section className={`section ${index%2===0?'section-dark':''}`} key={section.title}><div className="container"><SectionTitle eyebrow={section.eyebrow} title={section.title} body={section.body}/>{section.cards?<div className="grid-3">{section.cards.map(card=><FeatureCard key={card.title} title={card.title} body={card.body}/>)}</div>:null}</div></section>)}
    {faqs.length?<FAQList eyebrow={copy.eyebrow} title={copy.title} faqs={faqs}/>:null}
    {page!=='start'?<CTA title={copy.cta} body={copy.ctaBody} primaryLabel={ui.start} primaryHref={start} secondaryLabel={ui.nav['how-it-works']} secondaryHref={pagePath(locale,'how-it-works')}/>:null}
  </PageShell>;
}

const ruForm={notice:'Не отправляйте секретные чертежи, учётные данные или сведения без права распространения.',title:'Несекретный запрос на проверку',organization:'Юридическое лицо покупателя',role:'Ваша роль',country:'Страна регистрации и назначения',email:'Контактный e-mail',help:'Тип запроса',options:['Гражданский товар — поиск/RFQ','Образец и проверка','Качество и производство','Таможенные документы','Контролируемая логистика и склад'],issue:'Опишите товар, модель, HS-код, количество, плательщика, получателя, конечного пользователя, конечное использование, маршрут и банки',issuePlaceholder:'Укажите все известные стороны и полный маршрут. Не скрывайте транзит или конечное назначение.',sensitivity:'Чувствительность данных',sensitivityOptions:['Публичные / несекретные','Деловые данные — сначала согласовать обработку','Чувствительные — не отправлять здесь'],prepare:'Подготовить письмо',clear:'Очистить',open:'Открыть письмо',ready:'Письмо подготовлено. Проверьте его перед отправкой.',missing:'Заполните обязательные поля. Ничего не отправлено.',cleared:'Черновик очищен. Ничего не отправлено.',note:'Сайт ничего не отправляет автоматически. Запрос не означает приём задачи, договор или обязательство оплаты.'};

export function RussianPage({page}:{page:'home'|'sourcing'|'compliance'|'start'}){
  const ui=russianCopy;const copy=ui.pages[page];const path=page==='home'?'/ru':page==='sourcing'?'/ru/china-sourcing':page==='compliance'?'/ru/compliance-logistics':'/ru/start';
  const cards=('cards' in copy?copy.cards:undefined);
  return <PageShell locale="ru">
    {page==='sourcing'||page==='compliance'?<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Service',name:copy.title,description:copy.description,url:`https://seekapi.ai${path}`,provider:{'@id':'https://seekapi.ai/#organization'},areaServed:'China',inLanguage:'ru',termsOfService:'Lawful civilian, non-restricted goods only; manual compliance review required.'})}}/>:null}
    <section className={page==='home'?'hero localized-hero':'page-hero'}><div className="container"><Eyebrow>{copy.eyebrow}</Eyebrow><h1>{copy.heading}</h1><p className="lead">{page==='start'&&process.env.NEXT_PUBLIC_INQUIRIES_ENABLED==='1'?inquiryCopy.ru.intro:copy.lead}</p>{page!=='start'?<div className="button-row"><Link className="button" href="/ru/start">{ui.start}</Link><Link className="button button-ghost" href="/ru/compliance-logistics">Проверка условий</Link></div>:null}</div></section>
    {page==='start'?<section className="section section-tight"><div className="container"><Suspense fallback={<p>…</p>}><LocalizedStartForm copy={ruForm} russian/></Suspense></div></section>:<><section className="section section-dark"><div className="container"><SectionTitle eyebrow="Обязательные условия" title="Никакого обхода ограничений." body="SeekAPI не содействует ложному описанию товара, скрытию конечного пользователя или страны назначения, подмене плательщика или получателя, нераскрытому транзиту, запрещённым товарам или обходу санкций, экспортного контроля, таможенных и банковских правил."/>{cards?<div className="grid-2">{cards.map(card=><FeatureCard key={card.title} title={card.title} body={card.body}/>)}</div>:<div className="grid-3"><FeatureCard title="Гражданские товары" body="Точное описание, модель, характеристики, HS-код и законное конечное использование."/><FeatureCard title="Раскрытые стороны" body="Покупатель, плательщик, банки, получатель, конечный пользователь и посредники."/><FeatureCard title="Ручное решение" body="До контакта с поставщиком запрос может получить NEEDS_INFO, DECLINED или APPROVAL_REQUIRED."/></div>}</div></section><section className="section"><div className="container"><SectionTitle eyebrow="Граница ответственности" title="Координация не заменяет лицензированную проверку." body="SeekAPI собирает факты, ведёт список условий, координирует квалифицированных провайдеров, отслеживает этапы и сохраняет доказательства. Юридические заключения, экспортный контроль, налоговые решения, сертификацию и таможенные декларации выполняет клиент или надлежаще квалифицированная сторона. Автоматическое исполнение агентом и платежи не включены."/></div></section><CTA title="Начните с полной и несекретной информации." body="Ручная проверка проводится до контакта с поставщиком. Неполный или непрозрачный маршрут не принимается." primaryLabel={ui.start} primaryHref="/ru/start" secondaryLabel="English technical entry" secondaryHref="/for-agents"/></>}
  </PageShell>;
}
