import Link from 'next/link';
import { Suspense } from 'react';
import { CTA, FAQList, FeatureCard, PageShell, ProcessSteps, SectionTitle, ServiceFaqSchema, SplitPanel, type FaqItem } from './site';
import { ZhStartForm } from './zh-start-form';

const companyFaqs:FaqItem[]=[
  {question:'SeekAPI 是工厂或贸易商吗？',answer:'SeekAPI 的默认角色是中国侧的寻源、沟通、协调和证据管理服务商，不声称拥有工厂。若某个项目中 SeekAPI 作为货物卖方，该角色和产品价格必须单独写明。'},
  {question:'涉及认证、报关或税务时由谁负责？',answer:'SeekAPI 可以梳理路径、准备问题、协调资料和跟进节点；必须持牌的法律、税务、检测、认证、报关和运输工作由客户或合资格服务商完成。'},
  {question:'什么时候开始收费？',answer:'先做有限的适配判断。执行前书面确认项目范围、交付物、责任、费用和停止点；第三方费用必须另行批准。'}
];
const complianceFaqs:FaqItem[]=[
  {question:'SeekAPI 能保证注册、认证或清关成功吗？',answer:'不能。SeekAPI 负责路径梳理、资料协调、节点监控和证据留存，不保证监管审批、认证结论、清关、税务处理或运输时效。'},
  {question:'开始评估需要哪些信息？',answer:'通常需要产品、原产地、目的地、用途、销售渠道、贸易方向、预计数量和当前卡点。第一步不要发送敏感文件。'},
  {question:'可以同时处理物流、仓储和退货吗？',answer:'可以在约定范围内比较报价、监控运输节点、保存签收与库存证据，并协调隔离、复检、返工、索赔和逆向物流。'}
];
const agentFaqs:FaqItem[]=[
  {question:'现在有可以直接下单的人类任务 API 吗？',answer:'没有。当前公开入口是人工范围评估，尚未开放任务 API、MCP 或 WebMCP 自动执行。'},
  {question:'Agent 如何开始调用 SeekAPI？',answer:'Agent owner 或开发者先提交非敏感的任务类别、目标、允许动作、禁止动作、证据要求和审批联系人，再由人工确认是否接受。'},
  {question:'Agent 可以自行付款或接受质量偏差吗？',answer:'默认不可以。付款、合同变化、质量偏差和其他高风险动作必须来自明确的人类授权；本预览不提供付款。'}
];

export function ZhHome(){return <PageShell locale="zh">
  <section className="page-hero"><div className="container"><div className="eyebrow">API · 企业服务 · Agent 人工交接</div><h1>软件能走很远，现实世界仍然需要人。</h1><p>SeekAPI 是海外企业在中国的外部执行台：协助寻源、供应商沟通、合规路径、物流、仓储和履约。对于 AI Agent，我们把无法在软件中完成的中国现场任务，变成有权限边界、有负责人、有证据回传的人工交接。</p><div className="button-row"><Link className="button" href="/zh/china-supply-chain">企业服务</Link><Link className="button button-ghost" href="/zh/for-agents">Agent 服务</Link><Link className="button button-ghost" href="/zh/apis">API</Link></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="一个品牌，三个入口" title="先选择你真正需要完成的事情。"/><div className="grid-3"><FeatureCard title="海外企业" body="把中国寻源、供应商沟通、质量、合规、物流和异常处理交给一个明确责任边界的中国侧执行台。"/><FeatureCard title="AI Agent 与开发者" body="为必须由人完成的中国任务定义目标、权限、禁止动作、证据和审批路径。"/><FeatureCard title="机器能力" body="通过现有开发者文档、账户和控制台进入 SeekAPI 的软件产品；未上线能力会明确标注。"/></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="为什么需要 SeekAPI" title="找到供应商，只是第一步。" body="跨时区、语言、版本、法规、运输和异常会让一个看似简单的订单变成长期协调工作。SeekAPI 的价值是把当前事实、责任人、下一动作、费用和证据放在同一条工作线上。"/><div className="grid-3"><FeatureCard title="中国本地执行" body="中文沟通、现场协调、节点跟进和问题升级。"/><FeatureCard title="不替客户做越权决定" body="价格、付款、合同、工程和合规结论按约定留给有权人员。"/><FeatureCard title="可以明确说不" body="当成本、风险或控制方式不合适时，可以给出 NO-GO，而不是推动一笔不合理交易。"/></div></div></section>
  <CTA title="从一个非敏感的真实问题开始。" body="先判断 SeekAPI 是否适合，再决定是否进入付费执行。" primaryLabel="提交一个问题" primaryHref="/zh/start" secondaryLabel="查看信任边界" secondaryHref="/zh/trust"/>
</PageShell>}

export function ZhApis(){return <PageShell locale="zh">
  <section className="page-hero"><div className="container"><div className="eyebrow">面向开发者和机器</div><h1>通过代码使用 SeekAPI。</h1><p>现有开发者入口提供文档、账户和控制台。需要供应商沟通、现场核验或人工判断的任务，应转到单独的人工执行入口。</p><div className="button-row"><a className="button" href="https://seekapi.ai/docs">开发者文档</a><a className="button button-ghost" href="https://seekapi.ai/login">登录或创建账户</a></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="公开入口" title="软件能力与人工执行分开。"/><div className="grid-3"><FeatureCard title="文档" body="查看现有产品公开的认证、接口和接入说明。"/><FeatureCard title="账户" body="通过现有登录流程访问账户。"/><FeatureCard title="控制台与状态" body="登录后进入控制台，并通过公开状态页查看服务状态。"/></div><div className="link-list"><a className="text-link" href="https://seekapi.ai/docs">文档</a><a className="text-link" href="https://seekapi.ai/dashboard">控制台</a><a className="text-link" href="https://seekapi.ai/status">系统状态</a></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="能力真实性" title="沙盒通过，不等于已经上线。" body="目前没有证据支持在本网站展示一个新的公开调用 endpoint。SeekAPI 不会把内部样例、fixture 或计划中的能力写成 LIVE API。"/></div></section>
  <CTA title="任务越过软件边界了吗？" body="需要中国当地人员执行时，先准备一个有边界的人工交接。" primaryLabel="查看 Agent 人工执行" primaryHref="/zh/for-agents" secondaryLabel="提交任务草稿" secondaryHref="/zh/start?audience=agent"/>
</PageShell>}

export function ZhCompanies(){return <PageShell locale="zh">
  <ServiceFaqSchema name="中国供应链执行台" description="面向海外企业的中国寻源、供应商沟通、生产、合规、物流与履约协调。" path="/zh/china-supply-chain" faqs={companyFaqs} locale="zh"/>
  <section className="page-hero"><div className="container"><div className="eyebrow">企业服务</div><h1>你的外部中国供应链执行台。</h1><p>SeekAPI 不是某一家工厂。我们帮助海外企业在中国完成寻源、中文沟通、样品、质量、生产、合规、物流和交付协调，而不必一开始就建立完整的中国团队。</p><div className="button-row"><Link className="button" href="/zh/start?audience=company">从一个问题开始</Link><Link className="button button-ghost" href="/zh/china-desk">常驻中国事务台</Link></div></div></section>
  <section className="section" id="services"><div className="container"><SectionTitle eyebrow="服务范围" title="从供应商搜索，到可控履约。"/><div className="grid-3"><FeatureCard title="寻源与询价" body="澄清需求、寻找候选、执行授权询价并把报价变得可比较。"/><FeatureCard title="供应商沟通" body="在中国时区进行中文技术澄清、承诺记录、追踪和升级。"/><FeatureCard title="样品与 NPI" body="管理版本、问题、审批证据和量产准备。"/><FeatureCard title="质量与生产" body="协调检验、生产节点、偏差和纠正措施。"/><FeatureCard title="合规协调" body="梳理品牌、产品、许可、海关、税务和文件路径。"/><FeatureCard title="物流与仓储" body="比较总成本、监控运输、记录库存、批次、异常和索赔证据。"/><FeatureCard title="交付" body="核对包装、拼箱、文件和出货准备，不默认承担承运人或进口商角色。"/><FeatureCard title="退货与返工" body="协调隔离、复检、返工、换货、索赔和逆向物流。"/><FeatureCard title="异常恢复" body="当质量、交期或责任不清时，重新建立事实和恢复计划。"/></div></div></section>
  <FAQList eyebrow="常见问题" title="先把角色和责任说清楚。" faqs={companyFaqs}/><CTA title="从最小的真实问题开始。" body="一个非敏感问题就足以判断是否适合。" primaryLabel="准备企业请求" primaryHref="/zh/start?audience=company" secondaryLabel="合规与履约" secondaryHref="/zh/china-compliance-logistics"/>
</PageShell>}

export function ZhDesk(){return <PageShell locale="zh">
  <section className="page-hero"><div className="container"><div className="eyebrow">持续性企业服务</div><h1>不用先建立完整团队，也能拥有中国侧事务台。</h1><p>当供应商、样品、质量、生产、合规、库存和交付任务持续出现时，China Desk 把零散请求变成一套有负责人、有节奏、有证据的工作关系。</p><div className="button-row"><Link className="button" href="/zh/start?audience=company&intent=china-desk">申请事务台方案</Link><Link className="button button-ghost" href="/zh/china-supply-chain">先做一个项目</Link></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="启动方式" title="先用一个具体问题验证合作。"/><div className="grid-3"><FeatureCard index="01" title="项目冲刺" body="一个有范围、费用、交付物和停止点的中国侧任务。"/><FeatureCard index="02" title="识别重复工作" body="确认哪些问题持续发生，哪些决定仍由客户团队负责。"/><FeatureCard index="03" title="China Desk" body="把稳定的重复任务转为按月、按范围管理。"/></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="工作范围" title="容量围绕实际工作定义。"/><div className="grid-3"><FeatureCard title="明确责任人" body="每项已接受工作都有当前状态、下一动作和升级路径。"/><FeatureCard title="合规日历" body="记录续期、检测、备案、文件和客户审批节点。"/><FeatureCard title="物流控制" body="比较报价口径，监控提货、出运、清关、签收和异常。"/><FeatureCard title="仓储可见性" body="保存收货、库存、批次、放行和异常证据。"/><FeatureCard title="退货与索赔" body="协调隔离、复检、返工、替换和证据链。"/><FeatureCard title="适时内建团队" body="当稳定工作量足够大，建立客户自己的中国团队可能更合适。"/></div></div></section>
  <CTA title="把重复的中国侧工作放进一个责任台。" body="先提交非敏感描述，再确认服务范围。" primaryLabel="申请方案" primaryHref="/zh/start?audience=company&intent=china-desk" secondaryLabel="合规与物流" secondaryHref="/zh/china-compliance-logistics"/>
</PageShell>}

export function ZhCompliance(){return <PageShell locale="zh">
  <ServiceFaqSchema name="中国合规、市场准入与履约协调" description="面向海外企业的产品路径、品牌保护、海关文件、物流、仓储和市场进入协调。" path="/zh/china-compliance-logistics" faqs={complianceFaqs} locale="zh"/>
  <section className="page-hero"><div className="container"><div className="eyebrow">面向海外企业</div><h1>找到供应商之后，到生意真正跑通之间的工作。</h1><p>产品可能涉及注册、检测、标签、持牌经营者、海关资料、税务记录、受控运输和本地跟进。SeekAPI 梳理路径、协调合资格服务商，并让动作、证据、费用和异常保持可见。</p><div className="button-row"><Link className="button" href="/zh/start?audience=company&intent=compliance">检查中国合规路径</Link><Link className="button button-ghost" href="/zh/start?audience=company&intent=logistics">规划物流仓储</Link></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="两种贸易方向" title="先确认货物往哪里走。"/><div className="grid-3"><FeatureCard title="从中国采购并出口" body="关注供应商资格、产品与包装要求、出口文件、运输和目的国进口责任。"/><FeatureCard title="把产品卖进中国" body="关注主体、商标、产品准入、中文标签、渠道、税务和持续备案。"/><FeatureCard title="中国境内运营支持" body="协调本地供应商、仓库、承运商、检测和合资格专业机构。"/></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="合规与手续" title="在下单前建立路径。"/><div className="grid-3"><FeatureCard title="主体与许可" body="核对谁是买方、卖方、出口商、进口商、备案人或持牌运营者。"/><FeatureCard title="产品路径" body="识别检测、认证、注册、备案、标签和技术文件问题。"/><FeatureCard title="知识产权" body="协调中国商标检索、申请、授权边界、包装和防抢注事项。"/><FeatureCard title="合同与证据" body="记录签约主体、规格版本、检验标准、交付条件和索赔路径。"/><FeatureCard title="税务与单证" body="协调发票、付款路径、关务资料和专业税务意见。"/><FeatureCard title="持续义务" body="维护续期、变更、抽检、召回、渠道和记录保存清单。"/></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="物流与仓储" title="让运输、库存和异常可监控。"/><div className="grid-3"><FeatureCard title="可比较的物流报价" body="统一贸易条款、起运地、目的地、重量体积、附加费、保险和预计时效。"/><FeatureCard title="运输节点" body="跟踪提货、装运、离港、到港、清关、预约和签收证据。"/><FeatureCard title="仓储控制" body="约定收货检查、批次、库存报告、放行权限、盘点和异常处理。"/><FeatureCard title="受控货物" body="在需要时协调合资格机构处理电池、化学品、温控或其他特殊货物。"/><FeatureCard title="索赔证据" body="保存时间线、照片、签收、检验、数量和责任资料。"/><FeatureCard title="逆向物流" body="协调退货、隔离、复检、返工、替换、报废和海关影响。"/></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="提前避免" title="海外委托方容易忽略的问题。"/><div className="grid-3"><FeatureCard title="错误主体" body="合同方、收款方、生产方、出口方和证书持有人可能不是同一主体。"/><FeatureCard title="版本失控" body="报价、样品、图纸、标签和量产规格必须使用同一批准版本。"/><FeatureCard title="隐性物流成本" body="低运价可能未包含目的港费、偏远费、仓租、滞期和税费。"/><FeatureCard title="未经授权的替代" body="材料、部件、工艺或包装变化需要明确批准。"/><FeatureCard title="不可执行的索赔" body="只有抱怨没有时间线、照片、检验和责任文件，往往难以追索。"/><FeatureCard title="手续失效" body="注册、商标、许可、检测或授权到期会影响销售与清关。"/></div></div></section>
  <FAQList eyebrow="常见问题" title="协调不等于代替持牌资格。" faqs={complianceFaqs}/><CTA title="先做一次路径检查。" body="说明产品、原产地、目的地、用途、销售方式和当前卡点；第一步不要发送敏感文件。" primaryLabel="准备非敏感请求" primaryHref="/zh/start?audience=company&intent=compliance" secondaryLabel="邮件联系" secondaryHref="mailto:support@seekapi.ai"/>
</PageShell>}

export function ZhAgents(){return <PageShell locale="zh">
  <ServiceFaqSchema name="AI Agent 中国人工执行层" description="为 AI 团队提供有边界的中国供应链人工交接、核验和证据回传。" path="/zh/for-agents" faqs={agentFaqs} locale="zh"/>
  <section className="page-hero"><div className="container"><div className="eyebrow">Agent 与 AI 团队</div><h1>让你的 Agent 在中国拥有一双手。</h1><p>当任务需要中文沟通、现场核验、人工判断或持续追踪时，可以把它整理成一个有目标、权限、禁止动作、证据和审批人的交接。当前公开入口是人工范围评估，不声称已有自动任务 API。</p><div className="button-row"><Link className="button" href="/zh/start?audience=agent">准备中国任务</Link><a className="button button-ghost" href="/for-agents/agent-services.json">机器可读服务清单</a></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="交接触发条件" title="任务越过软件边界时，使用人。" body="搜索、比较和规划可以由软件完成；当工作需要联系真实供应商、看实物、判断现场情况或承担跟进责任时，进入人工执行。"/></div></section>
  <section className="section" id="task-types"><div className="container"><SectionTitle eyebrow="任务词汇" title="八类可描述的中国侧人工任务。"/><div className="grid-3">{['联系供应商','寻源与资格核验','执行询价','样品与 NPI 跟进','现场核验协调','质量与异常恢复','交付、物流与仓储','合规研究与人工核验'].map((title,i)=><FeatureCard index={`AH0${i+1}`} title={title} body="具体范围、地点、可用性、负责人和证据要求在接受任务前确认。" key={title}/>)}</div></div></section>
  <section className="section section-dark" id="handoff-spec"><div className="container"><SectionTitle eyebrow="最小交接合同" title="Agent 必须说明可以做什么、不能做什么。"/><ProcessSteps steps={[{title:'目标',body:'要解决的问题和完成标准。'},{title:'允许动作',body:'可以联系谁、可以询问或核验什么。'},{title:'禁止动作',body:'付款、合同、质量偏差等明确禁区。'},{title:'证据',body:'需要返回照片、报价、记录、时间或来源。'},{title:'升级路径',body:'出现例外时由哪个人批准。'}]}/></div></section>
  <section className="section" id="availability"><div className="container"><SectionTitle eyebrow="当前状态" title="人工评估预览。" body="可以通过邮件提出范围问题；结构化网页提交、通用覆盖、公开任务 API、MCP 和 WebMCP 自动执行尚未上线。"/><div className="link-list"><a className="text-link" href="mailto:support@seekapi.ai">邮件联系</a><Link className="text-link" href="/zh/trust">查看数据、角色和付款边界</Link></div></div></section>
  <FAQList eyebrow="常见问题" title="自动化不能跳过授权。" faqs={agentFaqs}/><CTA title="准备一个有边界的人工交接。" body="先在浏览器里整理非敏感草稿，再由你检查并决定是否发送邮件。" primaryLabel="准备 Agent 交接" primaryHref="/zh/start?audience=agent" secondaryLabel="服务清单" secondaryHref="/for-agents/agent-services.json"/>
</PageShell>}

export function ZhHow(){return <PageShell locale="zh"><section className="page-hero"><div className="container"><div className="eyebrow">如何运作</div><h1>从一个问题，到有控制的中国侧执行。</h1><p>每一步都应当说明输入、负责人、权限、证据和停止点。没有确认范围，不开始真实执行。</p></div></section><section className="section"><div className="container"><ProcessSteps steps={[{title:'提出一个问题',body:'只提供判断适配性需要的非敏感事实。'},{title:'有限适配判断',body:'判断适合、不适合或还缺什么信息。'},{title:'定义范围',body:'写明角色、交付物、时间、费用、第三方成本和停止点。'},{title:'确认权限',body:'明确资料可以给谁，允许做什么，哪些决定必须升级。'},{title:'执行并留证',body:'记录来源、时间、动作、未知项、偏差和当前状态。'},{title:'交付与决定',body:'客户获得结论、证据和下一步，而不只是供应商的回复。'},{title:'转为持续事务台',body:'只有重复工作稳定出现时，才进入按月服务。'}]}/></div></section><CTA title="从最窄的真实问题开始。" body="适配判断不等于接受任务。" primaryLabel="准备请求" primaryHref="/zh/start" secondaryLabel="信任边界" secondaryHref="/zh/trust"/></PageShell>}

export function ZhProof(){return <PageShell locale="zh"><section className="page-hero"><div className="container"><div className="eyebrow">证据与声明</div><h1>展示证据，也展示证据的边界。</h1><p>客户案例、内部演示、公开分析和示意流程不是同一种证据。SeekAPI 不会用示意内容冒充客户成果。</p></div></section><section className="section"><div className="container"><SectionTitle eyebrow="证据标签" title="先看它属于哪一类。"/><div className="grid-3"><FeatureCard title="已核验客户案例" body="只有获得授权并能核对范围、结果和限制时才能使用；本预览没有发布此类案例。"/><FeatureCard title="自费演示" body="使用明确写出的假设和费用完成，可证明流程，不证明客户采用。"/><FeatureCard title="公开资料分析" body="结论只覆盖列出的公开来源和日期。"/><FeatureCard title="示意流程" body="用于解释操作方式，不代表真实订单、工厂或收入。"/><FeatureCard title="未知" body="不能确认的内容明确标注未知，不用推测填空。"/><FeatureCard title="NO-GO" body="证据指向不适合时，应建议停止或使用其他路线。"/></div></div></section><section className="section section-dark"><div className="container"><SectionTitle eyebrow="示意案例" title="中国采购不一定更划算。" body="小批量订单即使单价更低，也可能被运费、检验、协调、进口不确定性和补货时间抵消。没有完整总成本就不应宣称节省。"/></div></section><CTA title="用一个小问题测试可信度。" body="先建立事实，再扩大权限。" primaryLabel="开始" primaryHref="/zh/start" secondaryLabel="查看信任规则" secondaryHref="/zh/trust"/></PageShell>}

export function ZhTrust(){return <PageShell locale="zh"><section className="page-hero"><div className="container"><div className="eyebrow">信任、数据与商业角色</div><h1>在行动之前，先说清谁负责什么。</h1><p>SeekAPI 通过明确授权、证据、角色和停止点建立信任，而不是通过未经支持的能力承诺。</p></div></section><section className="section"><div className="container"><SectionTitle eyebrow="数据与知识产权" title="内部查看，不等于可以对外转发。"/><div className="definition-grid"><div className="definition"><h3>最少资料</h3><p>适配阶段只收集完成判断需要的非敏感信息。</p></div><div className="definition"><h3>转发权限</h3><p>文件、版本、接收人、用途和转发权限应在对外发送前确认。</p></div><div className="definition"><h3>敏感内容</h3><p>图纸、账号、供应商秘密和受管制资料应先确认处理方式和接收方。</p></div><div className="definition"><h3>证据边界</h3><p>供应商陈述、公开来源、人工观察和专业机构结论需要分开标注。</p></div></div></div></section><section className="section section-dark"><div className="container"><SectionTitle eyebrow="付款" title="本预览没有付款入口。" body="任务范围、责任主体、费用、第三方成本和操作控制确认后，才可以讨论付款。任何支付工具都不能代替质量控制或争议处理。"/></div></section><section className="section"><div className="container"><SectionTitle eyebrow="合资格服务商边界" title="协调不能替代法律要求的资质。" body="法律意见、税务申报、审计、认证、实验室报告、报关和受监管运输等工作，只能由客户或合资格机构完成。SeekAPI 不保证审批、清关、税务、认证、时效或法律结果。"/></div></section><section className="section section-dark" id="who-we-are"><div className="container"><SectionTitle eyebrow="运营主体" title="公开品牌背后有明确法律主体。"/><div className="definition-grid"><div className="definition"><h3>法律主体</h3><p>SeekAPI Technology Limited</p></div><div className="definition"><h3>注册地址 / 联系地址</h3><p>Room P11, Flat 2C, 2/F, Hung To Ctr., 94–96 How Ming St., Kwun Tong, Kowloon, Hong Kong</p></div><div className="definition"><h3>客服邮箱</h3><p><a className="text-link" href="mailto:support@seekapi.ai">support@seekapi.ai</a></p></div><div className="definition"><h3>提供敏感资料前</h3><p>先确认服务范围、处理方式、接收人和负责机构。</p></div></div></div></section><CTA title="先做一次小规模信任测试。" body="从非敏感问题开始，只有下一步确实需要时才扩大权限。" primaryLabel="提交一个问题" primaryHref="/zh/start" secondaryLabel="查看证据规则" secondaryHref="/zh/proof"/></PageShell>}

export function ZhStart(){return <PageShell locale="zh"><section className="page-hero"><div className="container"><div className="eyebrow">从小范围开始</div><h1>提交一个中国侧问题。</h1><p>选择企业请求或 Agent 人工交接。网站会在浏览器内检查并整理邮件草稿，不会自动上传、接受任务或收费。</p></div></section><section className="section section-tight"><div className="container"><Suspense fallback={<div className="form-card">正在加载表单……</div>}><ZhStartForm/></Suspense></div></section></PageShell>}
