import Link from 'next/link';
import { CTA, Eyebrow, FeatureCard, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';

export const metadata = pageMetadata('China Supply Check — evidence-screened China platform shops', 'For $2.99 USDC, China Supply Check promises three product-qualified distinct platform shop candidates with observed price, MOQ, unit and evidence limits. Paid execution is not open yet.', '/china-supply-check');

export default function ChinaSupplyCheckPage() {
  return <PageShell>
    <section className="page-hero"><div className="container"><Eyebrow>China Supply Check · Agent product</Eyebrow><h1>Find China platform shop candidates with evidence you can inspect.</h1><p>Submit a confirmed text or model requirement, quantity and must-have conditions. The report screens 1688 listings for product fit, mandatory facts, minimum order quantity and unit basis, then deduplicates direct platform shop identities.</p><div className="button-row"><Link className="button" href="/china-supply-check/sample">Read a real-evidence sample</Link><a className="button button-ghost" href="https://api.seekapi.ai/mcp">Public MCP endpoint</a></div><p className="hero-note">Product information is public. New paid China Supply Check execution is not open yet; this page does not collect payment or start sourcing.</p></div></section>
    <section className="section"><div className="container"><SectionTitle eyebrow="Product contract" title="$2.99 USDC · three qualified distinct platform shops" body="Three product-qualified distinct 1688 platform shop candidates are the delivery promise. One or two additional candidates may appear when naturally found within the same bounded search; they are bonuses, not guaranteed."/><div className="grid-3"><FeatureCard index="01" title="Confirm the brief" body="State the item or model, quantity, unit, must-have conditions and whether substitutions are permitted."/><FeatureCard index="02" title="Screen the evidence" body="Check observed product attributes, quantity, MOQ and units. Remove duplicates and show why other results were excluded."/><FeatureCard index="03" title="Read the answer" body="See three primary platform shop candidates, optional bonus candidates, observed listing price and evidence provenance with explicit unknowns."/></div></div></section>
    <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Claim limits" title="A platform listing is evidence, not a supplier quotation." body="The direct b2b shop identifier identifies a distinct platform shop candidate. Company identity, manufacturer status, contactability, stock, lead time, certification and an actual quote remain unverified unless separate evidence establishes them. Display prices and MOQ are observed listing values at the stated unit; they can change."/><div className="button-row"><Link className="button button-ghost" href="/china-supply-check/sample">Inspect the five-section sample</Link></div></div></section>
    <section className="section"><div className="container"><SectionTitle eyebrow="Next action" title="Live RFQ Compare · future $19.90 service" body="After a completed China Supply Check, the customer may edit and confirm one RFQ and choose up to three shortlisted recipients. Future human outreach requires its own payment and exact authorization; no supplier reply or three quotations are guaranteed. This service is not currently available for purchase."/></div></section>
    <CTA title="Read the real-evidence sample." body="Four distinct platform shops were observed for a 500-piece 304 stainless M6 washer brief; the fourth was an optional bonus. Historical execution and the new sample are labeled separately." primaryLabel="View sample report" primaryHref="/china-supply-check/sample" secondaryLabel="Machine interfaces" secondaryHref="/apis"/>
  </PageShell>;
}
