import Link from 'next/link';
import { CTA, Eyebrow, FeatureCard, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';
export const metadata=pageMetadata('China procurement desk for overseas buyers and AI agents','Scope-based China-side supplier contact, RFQ, samples, procurement and export coordination for overseas buyers and agents.','/china-desk');
export default function Page(){return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>For overseas buyers and AI agents</Eyebrow><h1>Your China-side procurement desk.</h1><p>SeekAPI can review a bounded human assignment after a supplier shortlist: contacting selected suppliers, gathering and comparing RFQ replies, sample follow-up, supplier communication and China-side procurement or export coordination. Each request needs agreed scope, fee, authority and evidence before acceptance. Recurring work can move to a China Desk plan.</p><div className="button-row"><Link className="button" href="/start?audience=agent">Prepare an Agent handoff</Link><Link className="button button-ghost" href="/china-supply-chain">Start with a project</Link></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Current sourcing product" title="Need a supplier shortlist first?" body="China Supply Check returns three distinct evidence-backed China supplier candidates worth advancing to RFQ on success. Agent x402 payment is live at 2.99 USDC on Base; Public credit-card checkout is OFF and is not available to buy. The separately scoped human services below retain their own acceptance and authorization boundaries."/><div className="link-list"><Link href="/china-supply-check">China Supply Check</Link><Link href="/sourcing">Supplier sourcing guides</Link><Link href="/for-agents">MCP preparation</Link></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="How it starts" title="Prove the working relationship on one issue."/><div className="grid-3"><FeatureCard index="01" title="Project Sprint" body="One defined China-side assignment with an agreed fee, role, output and stopping point."/><FeatureCard index="02" title="Review the pattern" body="Confirm whether work is recurring, which tasks repeat, and where decisions still belong to your team."/><FeatureCard index="03" title="China Desk" body="Move recurring work into a monthly, scope-based operating plan."/></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Scope dimensions" title="Capacity is defined around the work." body="A Desk plan can define active workstreams, supplier count, task classes, response windows, review cadence, evidence and escalation contacts. Actual scope and service levels are agreed before work begins."/><div className="grid-3"><FeatureCard title="Named responsibility" body="A clear owner, current status, next action and escalation route for accepted work."/><FeatureCard title="Compliance calendar" body="Track agreed registrations, permits, certificates, tests, contracts, renewals and qualified providers."/><FeatureCard title="Logistics control" body="Normalize freight quotes and monitor shipment milestones, customs handoffs, storage costs and exceptions."/><FeatureCard title="Warehouse visibility" body="Track inbound evidence, stock, reservations, lots, aging, damaged or quarantined goods and outbound authority."/><FeatureCard title="Returns & recovery" body="Coordinate claims, return authorization, inspection, rework, replacement, recall support and reverse logistics."/><FeatureCard title="Right-sized structure" body="When stable workload justifies an internal team, that may become the better long-term choice."/></div></div></section>
  <CTA title="Turn recurring China-side work into one accountable desk." body="Begin with a non-sensitive description of the work. The preview form does not submit data." primaryLabel="Request a Desk plan" primaryHref="/start?audience=company&intent=china-desk" secondaryLabel="Compliance & logistics" secondaryHref="/china-compliance-logistics"/>
</PageShell>}
