import { CTA, Eyebrow, FeatureCard, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';
export const metadata=pageMetadata('SeekAPI Machine Interfaces','Review SeekAPI machine-readable service discovery and the verified status of API, MCP and human handoff capabilities.','/apis');
export default function Page(){return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>For developers and machines</Eyebrow><h1>Machine-readable status, without pretending planned means live.</h1><p>SeekAPI publishes a machine-readable description of the proposed China-side human execution service. The public Task API, MCP and WebMCP interfaces are not live. A company or AI team can currently prepare a user-reviewed email for manual scope review.</p><div className="button-row"><a className="button" href="/for-agents/agent-services.json">Read agent-services.json</a><a className="button button-ghost" href="/start?audience=agent">Prepare a manual handoff</a></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Verified public entries" title="What a machine can discover today." body="The manifest separates available informational surfaces from proposed task types and integrations that are not yet live."/><div className="grid-3"><FeatureCard title="Service discovery" body="agent-services.json describes purpose, geographic scope, required handoff fields, approval boundaries and possible output states."/><FeatureCard title="User-reviewed intake" body="The browser can prepare an email draft. The user reviews and sends it; the website does not submit or accept the task automatically."/><FeatureCard title="API / MCP status" body="Task API, MCP and WebMCP are explicitly marked planned_not_live. No endpoint, authentication or payment capability is claimed."/></div><div className="link-list"><a className="text-link" href="/for-agents/agent-services.json">Machine-readable service manifest</a><a className="text-link" href="/for-agents">Human Execution Layer</a><a className="text-link" href="/trust">Trust and authorization boundaries</a></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Capability truth" title="Live, preview and planned remain separate." body="A fixture, internal demo or future idea is not published as a live API. A public product API will receive documentation and a callable endpoint only after production evidence exists."/></div></section>
  <CTA title="Does the task require a real person in China?" body="Use the Human Execution page to define the task, authority and evidence required." primaryLabel="For Agents" primaryHref="/for-agents" secondaryLabel="Company services" secondaryHref="/china-supply-chain"/>
</PageShell>}
