import Link from 'next/link';
import { CTA, Eyebrow, FeatureCard, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';
export const metadata=pageMetadata('SeekAPI APIs for Developers','Use SeekAPI machine capabilities through the existing developer documentation, account flow and dashboard.','/apis');
export default function Page(){return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>For developers and machines</Eyebrow><h1>Use SeekAPI through code.</h1><p>The existing SeekAPI developer surface provides documentation, account access and a dashboard. Human execution is a separate route for work that cannot finish inside software.</p><div className="button-row"><a className="button" href="https://seekapi.ai/docs">Open developer docs</a><a className="button button-ghost" href="https://seekapi.ai/login">Create or access an account</a></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Verified public routes" title="Choose the machine entry you need." body="These destinations are currently published on seekapi.ai. Availability, models and commercial terms remain governed by the live product surface."/><div className="grid-3"><FeatureCard title="Documentation" body="Read authentication, endpoint and integration guidance on the current developer site."/><FeatureCard title="Account access" body="Sign in or register through the existing email-link flow."/><FeatureCard title="Dashboard" body="Access the current console and account information after authentication."/></div><div className="link-list"><a className="text-link" href="https://seekapi.ai/docs">Developer documentation</a><a className="text-link" href="https://seekapi.ai/login">Account access</a><a className="text-link" href="https://seekapi.ai/dashboard">Dashboard</a><a className="text-link" href="https://seekapi.ai/status">System status</a></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Capability truth" title="Live, preview and planned remain separate." body="A fixture, internal demo or future idea is not published as a live API. The human-task handoff described on this preview is manual-review only and has no public task endpoint."/></div></section>
  <CTA title="Does the task require a real person in China?" body="Use the Human Execution page to define the task, authority and evidence required." primaryLabel="For Agents" primaryHref="/for-agents" secondaryLabel="Company services" secondaryHref="/china-supply-chain"/>
</PageShell>}
