import Link from 'next/link';
import { CTA, Eyebrow, FAQList, FeatureCard, PageShell, SectionTitle, ServiceFaqSchema, type FaqItem } from '@/components/site';
import { pageMetadata } from '@/lib/site';
export const metadata=pageMetadata('China procurement execution arm for AI agents — MCP and human handoff','SeekAPI helps agents source China suppliers, then request scoped human RFQ, sample and procurement coordination. Live China Supply Check costs 2.99 USDC via x402; human tasks require acceptance.','/for-agents');
const faqs:FaqItem[]=[
 {question:'What does China Supply Check return?',answer:'A successful check returns three distinct evidence-backed China supplier candidates worth advancing to RFQ, with observed price basis, MOQ fit, supplier identity evidence where available and explicit unknowns. Supplier RFQ-worthiness and exact product qualification are separate.'},
 {question:'What can an agent do for free?',answer:'Initialize the public MCP endpoint, list tools, read discover_china_supply_check_v0 and prepare a normalized Product Brief with prepare_china_supply_check_v0. Preparation does not buy a check or contact a supplier.'},
 {question:'How much is the check and which payment path is live?',answer:'The existing x402 path is live at 2.99 USDC on Base. Stripe Checkout USD 2.99 is being enabled and is not available to buy. Confirm the exact brief and payment scope before the paid purchase/run flow.'},
 {question:'How are order results accessed?',answer:'status_china_supply_check_v0 and result_china_supply_check_v0 require independent signed-wallet authentication bound to the settled order. A payment proof or arbitrary order ID alone does not grant report access.'},
 {question:'Does the check send an RFQ or contact a supplier?',answer:'No. Supplier contact, RFQ execution and human China Desk work are separately scoped services. Their execution and payments are not activated by this screening purchase.'},
];
const prepare={name:'prepare_china_supply_check_v0',arguments:{draft:{input:{text:'304 stainless M6 flat washer'},quantity:500,unit:'pieces',must_match:[{attribute:'material',expected:'304 stainless steel'}],product_name:'M6 flat washer',model_or_reference:'M6',substitution_allowed:false}}};
export default function Page(){return <PageShell>
 <ServiceFaqSchema name="China Supply Check" description="Find and screen China suppliers for a product. Three distinct RFQ-worthy candidates with evidence on success. MCP-native; 2.99 USDC via x402 live. Stripe Checkout USD 2.99 is being enabled, not live." path="/for-agents" faqs={faqs}/>
 <section className="page-hero"><div className="container"><Eyebrow>AI agent China procurement</Eyebrow><h1>Your Agent’s China-side procurement arm.</h1><p>SeekAPI helps overseas buyers and AI agents handle the China side of procurement. Begin with a live China Supply Check for a successful evidence-backed shortlist of three suppliers worth advancing to RFQ. Then request separately scoped human help to contact suppliers, compare quotes, coordinate samples and move an approved procurement task forward.</p><div className="button-row"><Link className="button" href="#china-supply-check-mcp">Connect and prepare a free brief</Link><Link className="button button-ghost" href="/china-supply-check/sample">Inspect the paid acceptance example</Link></div></div></section>
 <section className="section" id="china-supply-check-mcp"><div className="container"><SectionTitle eyebrow="Streamable HTTP MCP" title="Discover, prepare, confirm, then purchase" body="Connect to https://api.seekapi.ai/mcp using a standard MCP client. Initialize the session and request tools/list. Call discover_china_supply_check_v0 with empty arguments to read the current availability, price and input contract before preparing or purchasing."/><pre className="code-block" aria-label="MCP server connection configuration">{JSON.stringify({mcpServers:{seekapi:{type:'http',url:'https://api.seekapi.ai/mcp'}}},null,2)}</pre><p>This configuration uses a common MCP client shape; use your client's Streamable HTTP configuration if its field names differ. No API key is needed for public discovery.</p><div className="grid-2"><FeatureCard title="Prepare the requirement" body="prepare_china_supply_check_v0 accepts text or a model/part number, positive quantity and unit, up to five required attribute/value conditions, product name, optional reference and substitution permission. Review the normalized draft and digest before confirming."/><FeatureCard title="Use the existing paid path" body="purchase_china_supply_check_v0 and run_china_supply_check_v0 require separate exact scope and payment confirmation. The current price is 2.99 USDC on Base via live x402. Stripe Checkout USD 2.99 is being enabled and is not open for purchase."/></div><h2>A free preparation example</h2><pre className="code-block" aria-label="China Supply Check MCP prepare example">{JSON.stringify(prepare,null,2)}</pre><p>This is the parameters object for MCP tools/call after initialization. It prepares a brief; it does not execute a paid run, send an RFQ or contact a supplier.</p></div></section>
 <section className="section section-dark"><div className="container"><SectionTitle title="Preserve the meaning of the evidence" body="Observed listing prices are dated supplier commercial evidence with currency, unit, tier and MOQ conditions. Certification, company and production-versus-trade identity evidence is reported per candidate when available. Keep gaps attached to their fields. A successful check returns three RFQ-worthy supplier candidates; exact product qualification is separate, and unsupported shortages are reported honestly."/><p>Read status_china_supply_check_v0 and result_china_supply_check_v0 only with independent signed-wallet authentication bound to the settled order. Payment proof alone is not authentication.</p><div className="link-list"><Link href="/china-supply-check">Current product and purchase requirements</Link><Link href="/sourcing/china-procurement-mcp">MCP procurement workflow</Link><Link href="/sourcing/china-supplier-api">Developer response semantics</Link><Link href="/discovery-status">Dated directory evidence</Link></div></div></section>
 <section className="section" id="agent-human-desk"><div className="container"><SectionTitle eyebrow="Continue in China" title="A manual handoff is available for work beyond screening." body="Ask SeekAPI to scope supplier outreach, a confirmed RFQ, quote comparison, sample or production follow-up, procurement coordination and export handoffs. A person reviews fit, role, fee, recipients and authority before any task is accepted. Human-task API, MCP and WebMCP execution are not live; the live CSC MCP does not trigger supplier contact."/><div className="grid-3"><FeatureCard title="1 · Live check" body="Use the current CSC MCP and x402 path for evidence-backed supplier candidates; no outreach is included."/><FeatureCard title="2 · Human scope review" body="Prepare a request with the chosen candidates, RFQ draft, permitted actions, budget and evidence requested. The browser makes a reviewable email draft; it sends nothing on its own."/><FeatureCard title="3 · Accepted execution" body="After a separate agreement, a human China-side desk can coordinate approved contact, quotes, samples and the next procurement or export handoff. The fixed-price Live RFQ Compare package remains planned and is not open for purchase." /></div><div className="link-list"><Link href="/start?audience=agent">Prepare an Agent handoff request</Link><Link href="/china-desk">China Desk service</Link><Link href="/china-supply-chain">China-side scope</Link><Link href="/for-agents/agent-services.json">Machine-readable human service status</Link></div></div></section>
 <FAQList eyebrow="Current product facts" title="Know the output, price and permissions" faqs={faqs}/><CTA title="Prepare a China supplier brief" body="Start with the current discovery contract, then confirm a normalized product requirement. Supplier contact is a separate decision." primaryLabel="Read the product" primaryHref="/china-supply-check" secondaryLabel="Inspect the evidence example" secondaryHref="/china-supply-check/sample"/>
 </PageShell>}
