import Link from 'next/link';
import { CTA, Eyebrow, FAQList, FeatureCard, PageShell, SectionTitle, ServiceFaqSchema, type FaqItem } from '@/components/site';
import { pageMetadata } from '@/lib/site';
export const metadata=pageMetadata('China supplier sourcing MCP for AI agents','Find and screen China suppliers with MCP. A successful China Supply Check returns three RFQ-worthy candidates with evidence. x402 2.99 USDC live; Stripe Checkout USD 2.99 being enabled.','/for-agents');
const faqs:FaqItem[]=[
 {question:'What does China Supply Check return?',answer:'A successful check returns three distinct evidence-backed China supplier candidates worth advancing to RFQ, with observed price basis, MOQ fit, supplier identity evidence where available and explicit unknowns. Supplier RFQ-worthiness and exact product qualification are separate.'},
 {question:'What can an agent do for free?',answer:'Initialize the public MCP endpoint, list tools, read discover_china_supply_check_v0 and prepare a normalized Product Brief with prepare_china_supply_check_v0. Preparation does not buy a check or contact a supplier.'},
 {question:'How much is the check and which payment path is live?',answer:'The existing x402 path is live at 2.99 USDC on Base. Stripe Checkout USD 2.99 is being enabled and is not available to buy. Confirm the exact brief and payment scope before the paid purchase/run flow.'},
 {question:'How are order results accessed?',answer:'status_china_supply_check_v0 and result_china_supply_check_v0 require independent signed-wallet authentication bound to the settled order. A payment proof or arbitrary order ID alone does not grant report access.'},
 {question:'Does the check send an RFQ or contact a supplier?',answer:'No. Supplier contact, RFQ execution and human China Desk work are separately scoped services. Their execution and payments are not activated by this screening purchase.'},
];
const prepare={name:'prepare_china_supply_check_v0',arguments:{draft:{input:{text:'304 stainless M6 flat washer'},quantity:500,unit:'pieces',must_match:[{attribute:'material',expected:'304 stainless steel'}],product_name:'M6 flat washer',model_or_reference:'M6',substitution_allowed:false}}};
export default function Page(){return <PageShell>
 <ServiceFaqSchema name="China Supply Check" description="Find and screen China suppliers for a product. Three distinct RFQ-worthy candidates with evidence on success. MCP-native; 2.99 USDC via x402 live. Stripe Checkout USD 2.99 is being enabled, not live." path="/for-agents" faqs={faqs}/>
 <section className="page-hero"><div className="container"><Eyebrow>AI agent China sourcing</Eyebrow><h1>Source China suppliers through MCP.</h1><p>Give a product or model, quantity and must-have specifications. A successful China Supply Check returns three distinct evidence-backed China supplier candidates worth advancing to RFQ. Read the evidence and unknowns before choosing your next inquiry.</p><div className="button-row"><Link className="button" href="#china-supply-check-mcp">Connect and prepare a free brief</Link><Link className="button button-ghost" href="/china-supply-check/sample">Inspect the paid acceptance example</Link></div></div></section>
 <section className="section" id="china-supply-check-mcp"><div className="container"><SectionTitle eyebrow="Streamable HTTP MCP" title="Discover, prepare, confirm, then purchase" body="Connect to https://api.seekapi.ai/mcp using a standard MCP client. Initialize the session and request tools/list. Call discover_china_supply_check_v0 with empty arguments to read the current availability, price and input contract before preparing or purchasing."/><pre className="code-block" aria-label="MCP server connection configuration">{JSON.stringify({mcpServers:{seekapi:{type:'http',url:'https://api.seekapi.ai/mcp'}}},null,2)}</pre><p>This configuration uses a common MCP client shape; use your client's Streamable HTTP configuration if its field names differ. No API key is needed for public discovery.</p><div className="grid-2"><FeatureCard title="Prepare the requirement" body="prepare_china_supply_check_v0 accepts text or a model/part number, positive quantity and unit, up to five required attribute/value conditions, product name, optional reference and substitution permission. Review the normalized draft and digest before confirming."/><FeatureCard title="Use the existing paid path" body="purchase_china_supply_check_v0 and run_china_supply_check_v0 require separate exact scope and payment confirmation. The current price is 2.99 USDC on Base via live x402. Stripe Checkout USD 2.99 is being enabled and is not open for purchase."/></div><h2>A free preparation example</h2><pre className="code-block" aria-label="China Supply Check MCP prepare example">{JSON.stringify(prepare,null,2)}</pre><p>This is the parameters object for MCP tools/call after initialization. It prepares a brief; it does not execute a paid run, send an RFQ or contact a supplier.</p></div></section>
 <section className="section section-dark"><div className="container"><SectionTitle title="Preserve the meaning of the evidence" body="Observed listing prices are dated supplier commercial evidence with currency, unit, tier and MOQ conditions. Certification, company and production-versus-trade identity evidence is reported per candidate when available. Keep gaps attached to their fields. A successful check returns three RFQ-worthy supplier candidates; exact product qualification is separate, and unsupported shortages are reported honestly."/><p>Read status_china_supply_check_v0 and result_china_supply_check_v0 only with independent signed-wallet authentication bound to the settled order. Payment proof alone is not authentication.</p><div className="link-list"><Link href="/china-supply-check">Current product and purchase requirements</Link><Link href="/sourcing/china-procurement-mcp">MCP procurement workflow</Link><Link href="/sourcing/china-supplier-api">Developer response semantics</Link><Link href="/discovery-status">Dated directory evidence</Link></div></div></section>
 <section className="section" id="agent-human-desk"><div className="container"><SectionTitle title="When the next step needs a person" body="Supplier outreach, sample follow-up, physical inspection and broader China-side coordination require separately agreed scope and authority. Human-task API, MCP and WebMCP execution are not live. The screening check does not activate them."/><div className="link-list"><Link href="/china-desk">Separate China Desk service</Link><Link href="/china-supply-chain">Company service scope</Link><Link href="/for-agents/agent-services.json">Planned human-service manifest</Link></div></div></section>
 <FAQList eyebrow="Current product facts" title="Know the output, price and permissions" faqs={faqs}/><CTA title="Prepare a China supplier brief" body="Start with the current discovery contract, then confirm a normalized product requirement. Supplier contact is a separate decision." primaryLabel="Read the product" primaryHref="/china-supply-check" secondaryLabel="Inspect the evidence example" secondaryHref="/china-supply-check/sample"/>
 </PageShell>}
