import Link from 'next/link';
import { CTA, Eyebrow, FAQList, FeatureCard, PageShell, SectionTitle, ServiceFaqSchema, type FaqItem } from '@/components/site';
import { pageMetadata } from '@/lib/site';
export const metadata=pageMetadata('China Supply Check MCP for AI Agents | SeekAPI','Prepare a free China sourcing brief over MCP. A paid check screens three distinct China B2B shop candidates with observed listing price, MOQ and specification evidence.','/for-agents');
const tasks=[
 ['AH01','Supplier contact','Contact a named supplier and return structured answers without changing commercial terms.'],
 ['AH02','Discovery & qualification','Find candidates, check available evidence and return capability gaps and unknowns.'],
 ['AH03','RFQ execution','Send an approved revision to approved recipients and normalize responses.'],
 ['AH04','Sample / NPI follow-up','Track sample status, revision, issues and buyer approval evidence.'],
 ['AH05','Physical verification coordination','Coordinate observable evidence or qualified third-party inspection where available.'],
 ['AH06','Quality / exception recovery','Follow up on delay, rework, nonconformance or loss of communication.'],
 ['AH07','Delivery, logistics & warehousing','Coordinate packaging, freight, shipment milestones, warehouse evidence, inventory status and local readiness within the agreed role.'],
 ['AH08','Compliance research + human verification','Add human verification to entity, license, product-path, document, contact or other critical business facts.'],
];
const handoff=`requester_type: agent
organization: example_ai_team
objective: confirm_sample_revision_status
task_type: AH01
context_summary: illustrative_only
allowed_actions: [contact_supplier, request_status]
prohibited_actions: [change_terms, make_payment, accept_deviation]
recipient_permissions: [named_supplier]
max_budget: null
deadline: null
required_evidence: [supplier_response, photo_if_available]
completion_definition: status_and_open_questions_returned
human_approval_contact: required`;
const receipt=`status: COMPLETED | PARTIAL | BLOCKED | DECLINED
actions_taken: [{actor_type, action, timestamp}]
findings: []
evidence: [{source, created_by, timestamp, limitation}]
costs: {approved: 0, actual: 0, third_party: 0}
open_questions: []
exceptions: []
next_decision: null`;
const faqs:FaqItem[]=[{question:'Is a public human-task API live?',answer:'No. The current public route is manual scope review. Human-task API, MCP and WebMCP execution are not live on this preview. Product-data MCP discovery is documented separately on the APIs page.'},{question:'How does an Agent start?',answer:'The Agent owner or developer prepares a non-sensitive task class, objective, allowed actions, prohibited actions, evidence requirements and human approval contact for manual review.'},{question:'Can an Agent authorize payment or accept a quality deviation?',answer:'Not by default. Payment, contract changes, quality deviations and other high-risk actions require explicit human authority. Human-task payments are not available in this preview; the separately confirmed China Supply Check is available for 2.99 USDC.'}];
export default function Page(){return <PageShell>
  <ServiceFaqSchema name="China Human Execution Layer for AI Agents" description="Bounded human handoffs, verification and evidence return for AI teams with China-side tasks." path="/for-agents" faqs={faqs}/>
  <section className="page-hero"><div className="container"><Eyebrow>For Agents & AI teams</Eyebrow><h1>Start a China sourcing check with a free Product Brief.</h1><p>Give the public MCP tool a written product or model, quantity and hard specifications. Free preparation returns a confirmation draft and digest. A completed paid check screens three distinct China B2B shop candidates with linked observed price, MOQ and specification evidence. A paid order requires separate scope and payment confirmation; human supplier outreach is a separate service.</p><div className="button-row"><Link className="button" href="#china-supply-check-mcp">Connect free MCP</Link><Link className="button button-ghost" href="/china-supply-check/sample">Inspect the sample summary</Link></div></div></section>
  <section className="section" id="china-supply-check-mcp"><div className="container"><SectionTitle eyebrow="Public MCP · free preparation · paid check" title="Prepare, confirm and run a China Supply Check." body="Connect a Streamable HTTP MCP client to https://api.seekapi.ai/mcp. Public paid access is open with continuous admission. Discover and prepare are free; a separately confirmed paid check costs 2.99 USDC on Base. The public tools are discover_china_supply_check_v0, prepare_china_supply_check_v0, purchase_china_supply_check_v0, run_china_supply_check_v0, status_china_supply_check_v0 and result_china_supply_check_v0. Read the live discovery contract before purchase. A successful report returns three RFQ-worthy platform-shop supplier candidates."/><div className="grid-2"><FeatureCard title="What to provide" body="Text product description or model/part number, positive quantity and unit, up to five required attribute/value conditions, product name, optional reference and substitution permission. The normalized draft needs exact buyer or delegated Agent confirmation before a paid run."/><FeatureCard title="What to expect now" body="Prepare returns a deterministic draft digest with zero Provider and payment effects. Purchase and run require separate exact scope and payment confirmation. Status and result require independent signed wallet authentication bound to the settled order; a payment proof or arbitrary order ID alone gives no report."/></div><pre className="code-block" aria-label="Free China Supply Check MCP prepare example">{JSON.stringify({name:'prepare_china_supply_check_v0',arguments:{draft:{input:{text:'304 stainless M6 flat washer'},quantity:500,unit:'pieces',must_match:[{attribute:'material',expected:'304 stainless steel'}],product_name:'M6 flat washer',model_or_reference:'M6',substitution_allowed:false}}},null,2)}</pre><p>Observed listing prices are published supplier commercial evidence with currency, unit, tier and MOQ conditions; certification and company or production-versus-trade identity are reported per candidate when available. China Supply Check costs 2.99 USDC per accepted order via x402 after separate scope and payment confirmation, with Stripe card checkout being enabled. The USD 19.90 Live RFQ Compare remains planned and is not open for purchase. <Link className="text-link" href="/china-supply-check">Read the product and price boundaries</Link>.</p></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Handoff trigger" title="Use a human when the task crosses the software boundary." body="Software can research, compare and plan. Human execution becomes relevant when the work requires Chinese-language contact, a physical observation, commercial authority, judgment or persistence across several people."/></div></section>
  <section className="section" id="task-types"><div className="container"><SectionTitle eyebrow="Proposed task classes" title="Eight task types, each subject to scope review." body="These classes define the service vocabulary. They do not claim universal availability, location coverage or automatic acceptance."/><div className="grid-2">{tasks.map(([id,title,body])=><FeatureCard key={id} index={id} title={title} body={body}/>)}</div></div></section>
  <section className="section section-dark" id="handoff-spec"><div className="container"><SectionTitle eyebrow="Illustrative handoff" title="State what humans may do, must return and must never infer." body="Contact authority does not imply RFQ, spending, contract or production authority. Sensitive files are excluded from this preview."/><pre className="code-block" aria-label="Illustrative structured agent handoff">{handoff}</pre></div></section>
  <section className="section" id="evidence-return"><div className="container"><SectionTitle eyebrow="Illustrative evidence return" title="“Done” is not a sufficient result." body="A completed or blocked task should return actions, sources, limitations, costs, unknowns and the next decision."/><pre className="code-block" aria-label="Illustrative evidence return">{receipt}</pre></div></section>
  <section className="section section-dark" id="agent-human-desk"><div className="container"><SectionTitle eyebrow="Agent Human Desk" title="Reserved human execution capacity under agreed permissions." body="For AI teams with recurring China-side work, a Desk can define task classes, concurrent work, response windows, evidence, escalation contacts and spending authority. Scope and service levels require agreement; this preview is not a live subscription."/><div className="button-row"><Link className="button" href="/start?audience=agent&intent=agent-human-desk">Request an Agent Human Desk</Link></div></div></section>
  <section className="section" id="availability"><div className="container"><SectionTitle eyebrow="Current state" title="Manual review preview." body="The task vocabulary, permissions and evidence format are defined. Manual scope questions can be sent by email, but structured web intake, universal coverage, public human-task API, human-task MCP and WebMCP execution are not live on this preview."/><div className="link-list"><Link className="text-link" href="/apis#product-search">Product-data MCP discovery (no payment)</Link><Link className="text-link" href="/china-supply-check">China Supply Check</Link><Link className="text-link" href="/discovery-status">CSC discovery status</Link><a className="text-link" href="mailto:support@seekapi.ai">Email support@seekapi.ai</a><Link className="text-link" href="/china-compliance-logistics">Compliance, logistics and warehousing</Link><Link className="text-link" href="/trust">Data, role and payment boundaries</Link><Link className="text-link" href="/how-it-works">See the complete operating path</Link></div></div></section>
  <FAQList eyebrow="Common questions" title="Automation does not bypass authority." faqs={faqs}/>
  <CTA title="Prepare a bounded handoff." body="Validate a non-sensitive draft in the browser. Nothing is submitted or accepted in this preview." primaryLabel="Draft an Agent handoff" primaryHref="/start?audience=agent" secondaryLabel="Read the manifest" secondaryHref="/for-agents/agent-services.json"/>
</PageShell>}
