import Link from 'next/link';
import { CTA, Eyebrow, FeatureCard, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';
export const metadata=pageMetadata('China Supply Chain Desk','External sourcing, supplier communication and manufacturing coordination in China.','/china-supply-chain');
export default function Page(){return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>For Companies</Eyebrow><h1>Your external China supply-chain desk.</h1><p>SeekAPI is not a single factory. It is a China-side sourcing, supplier communication and manufacturing coordination service for companies that need local execution without building a full local team first.</p><div className="button-row"><Link className="button" href="/start?audience=company">Start with one issue</Link><Link className="button button-ghost" href="/china-desk">Ongoing China Desk</Link></div></div></section>
  <section className="section" id="services"><div className="container"><SectionTitle eyebrow="What we handle" title="Six points where China-side work gets stuck."/><div className="grid-3"><FeatureCard title="Sourcing & RFQ" body="Clarify the requirement, identify candidates, send an authorized RFQ and normalize the replies."/><FeatureCard title="Supplier communication" body="Chinese-language follow-up, technical clarification, commitments and escalation in the local time zone."/><FeatureCard title="Sample & NPI" body="Track revision, questions, approval evidence and readiness to move beyond the sample."/><FeatureCard title="Quality & production" body="Coordinate inspection evidence, milestones, deviations and supplier corrective follow-up."/><FeatureCard title="Delivery coordination" body="Check packaging, consolidation, documents and shipment readiness without assuming a carrier or importer role."/><FeatureCard title="Trouble recovery" body="Re-establish facts, responsibility and a recovery plan when communication, quality or delivery is unclear."/></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Commercial path" title="Fit first. Paid execution when China-side work begins."/><div className="grid-3"><FeatureCard index="01" title="Limited fit review" body="We determine fit, no-go or missing information before execution."/><FeatureCard index="02" title="Project Sprint" body="A defined project fee, role, deliverable and stop point are agreed before action."/><FeatureCard index="03" title="China Desk" body="Recurring work can move to monthly, scope-based support. Third-party costs are separately approved."/></div><p>Our normal service fee does not depend on disclosure of your historical purchase price. When SeekAPI acts as a seller of goods, that role and product price must be explicit.</p></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="Control and outputs" title="A supplier reply is an input, not the finish line."/><div className="definition-grid"><div className="definition"><h3>Inputs and rights</h3><p>File revision, intended recipients, purpose and forwarding permission are established before an external RFQ. Internal review does not authorize forwarding.</p></div><div className="definition"><h3>Outputs</h3><p>Comparable options, recorded actions, evidence sources, deviations, unknowns, costs and the next buyer decision.</p></div><div className="definition"><h3>NO-GO</h3><p>We can recommend staying local, stopping a supplier route or building an internal team when the economics or control model does not fit.</p></div><div className="definition"><h3>Human responsibility</h3><p>Accepted work has a responsible owner. Product, regulatory and engineering decisions remain with the qualified party defined for the project.</p></div></div><div className="link-list"><Link className="text-link" href="/how-it-works">See the operating process</Link><Link className="text-link" href="/proof">See evidence labels and examples</Link><Link className="text-link" href="/trust#data-ip">Read the data and authorization model</Link><Link className="text-link" href="/for-agents#task-types">Building an agent? See task types</Link></div></div></section>
  <CTA title="Start with the narrowest real problem." body="One non-sensitive issue is enough to decide whether SeekAPI is the right China-side route." primaryHref="/start?audience=company" secondaryLabel="Trust and roles" secondaryHref="/trust"/>
</PageShell>}
