import type { Locale } from './core';
const keys=['title','intro','name','email','country','message','details','files','fileHelp','submit','submitting','received','reference','boundary','consent','error','remove','restart','company','agent','permissions','compliance'] as const;
const rows:Record<Locale,string[]>={
 en:['Tell us what you need','No account needed. Start with a short description; add details and files if helpful.','Your name','Email','Country / region','Your request and desired outcome','Add company, contact and project details (optional)','Attachments','Up to 10 files; 20 MB each; 100 MB total. JPG, PNG, WebP, PDF, TXT, CSV, DOCX, XLSX, PPTX. Drag files here or choose files.','Submit inquiry','Submitting…','Thank you. We have received your inquiry. Our team will carefully review your requirements and contact you as soon as possible.','Inquiry reference','Submitting an inquiry does not authorize supplier contact, accept a task, create a contract or authorize payment.','I have the right to share this information and agree to its use for reviewing and responding to my inquiry as described in the privacy notice.','Submission could not be completed. Your fields are retained. Retry, or contact support@seekapi.ai.','Remove','Edit details / start a new upload session','Company','Agent / AI team','Agent permissions and evidence','I confirm lawful civilian use and disclose all parties, end users, destinations and routes. I am not requesting evasion of restrictions.'],
 ja:['ご要望をお聞かせください','アカウント登録は不要です。まず概要を入力し、必要に応じて詳細や資料を追加してください。','お名前','メールアドレス','国・地域','ご依頼内容と希望する成果','会社・連絡先・案件の詳細を追加（任意）','添付資料','最大10件、1件20MB、合計100MB。JPG、PNG、WebP、PDF、TXT、CSV、DOCX、XLSX、PPTX。ドラッグまたはファイル選択。','問い合わせを送信','送信中…','お問い合わせを受け付けました。ご要望を慎重に確認し、できるだけ早くご連絡いたします。','問い合わせ番号','送信はサプライヤーへの連絡許可、業務の受諾、契約締結、支払承認を意味しません。','この情報を共有する権限があり、プライバシー通知に従って問い合わせの確認・回答に利用されることに同意します。','送信を完了できませんでした。入力内容は保持されています。再試行するか support@seekapi.ai にご連絡ください。','削除','内容を編集・アップロードを再開','企業','エージェント・AIチーム','エージェントの権限と証拠','合法的な民生用途であり、関係者・最終利用者・仕向地・経路を開示します。規制回避は依頼しません。'],
 es:['Cuéntenos qué necesita','No necesita una cuenta. Describa su necesidad y añada detalles o archivos si le resultan útiles.','Su nombre','Correo electrónico','País / región','Su solicitud y resultado esperado','Añadir datos de empresa, contacto y proyecto (opcional)','Archivos adjuntos','Hasta 10 archivos; 20 MB cada uno; 100 MB en total. JPG, PNG, WebP, PDF, TXT, CSV, DOCX, XLSX, PPTX. Arrastre o seleccione archivos.','Enviar consulta','Enviando…','Hemos recibido su consulta. Evaluaremos detenidamente sus necesidades y nos pondremos en contacto con usted lo antes posible.','Referencia de consulta','Enviar una consulta no autoriza contactos con proveedores, acepta tareas, crea contratos ni autoriza pagos.','Tengo derecho a compartir esta información y acepto su uso para evaluar y responder a mi consulta según el aviso de privacidad.','No se pudo completar el envío. Sus datos se conservan. Reinténtelo o contacte con support@seekapi.ai.','Eliminar','Editar datos / iniciar una nueva carga','Empresa','Agente / equipo de IA','Permisos y evidencias del agente','Confirmo un uso civil lícito y declaro todas las partes, usuarios finales, destinos y rutas. No solicito eludir restricciones.'],
 ar:['أخبرنا بما تحتاجه','لا تحتاج إلى حساب. ابدأ بوصف موجز وأضف التفاصيل والملفات حسب الحاجة.','الاسم','البريد الإلكتروني','الدولة / المنطقة','طلبك والنتيجة المطلوبة','إضافة تفاصيل الشركة والتواصل والمشروع (اختياري)','المرفقات','حتى 10 ملفات؛ 20 ميغابايت لكل ملف؛ 100 ميغابايت إجمالاً. JPG، PNG، WebP، PDF، TXT، CSV، DOCX، XLSX، PPTX. اسحب الملفات أو اخترها.','إرسال الاستفسار','جارٍ الإرسال…','لقد تلقينا استفسارك. سنقيّم متطلباتك بعناية ونتواصل معك في أقرب وقت ممكن.','رقم الاستفسار','إرسال الاستفسار لا يجيز التواصل مع الموردين ولا يعني قبول المهمة أو إبرام عقد أو الإذن بالدفع.','لدي الحق في مشاركة هذه المعلومات وأوافق على استخدامها لتقييم استفساري والرد عليه وفق إشعار الخصوصية.','تعذر إكمال الإرسال. بياناتك محفوظة في النموذج. حاول مجدداً أو تواصل عبر support@seekapi.ai.','إزالة','تعديل التفاصيل / بدء رفع جديد','شركة','وكيل / فريق ذكاء اصطناعي','صلاحيات الوكيل والأدلة','أؤكد الاستخدام المدني المشروع وأفصح عن جميع الأطراف والمستخدمين النهائيين والوجهات والمسارات، ولا أطلب التحايل على القيود.'],
 de:['Beschreiben Sie Ihren Bedarf','Kein Konto erforderlich. Beginnen Sie mit einer kurzen Beschreibung und ergänzen Sie bei Bedarf Details und Dateien.','Ihr Name','E-Mail','Land / Region','Ihre Anfrage und das gewünschte Ergebnis','Unternehmens-, Kontakt- und Projektdetails ergänzen (optional)','Anhänge','Bis zu 10 Dateien; je 20 MB; insgesamt 100 MB. JPG, PNG, WebP, PDF, TXT, CSV, DOCX, XLSX, PPTX. Dateien hierher ziehen oder auswählen.','Anfrage absenden','Wird gesendet…','Wir haben Ihre Anfrage erhalten. Wir prüfen Ihren Bedarf sorgfältig und melden uns so bald wie möglich bei Ihnen.','Anfragenummer','Eine Anfrage erteilt keine Erlaubnis zur Lieferantenkontaktaufnahme und ist weder Auftragsannahme noch Vertrag oder Zahlungsfreigabe.','Ich darf diese Informationen weitergeben und stimme ihrer Verwendung zur Prüfung und Beantwortung meiner Anfrage gemäß dem Datenschutzhinweis zu.','Das Senden konnte nicht abgeschlossen werden. Ihre Eingaben bleiben erhalten. Versuchen Sie es erneut oder schreiben Sie an support@seekapi.ai.','Entfernen','Angaben bearbeiten / Upload neu starten','Unternehmen','Agent / KI-Team','Agent-Berechtigungen und Nachweise','Ich bestätige eine rechtmäßige zivile Nutzung und lege alle Parteien, Endnutzer, Ziele und Routen offen. Ich beantrage keine Umgehung von Beschränkungen.'],
 'pt-BR':['Conte-nos o que você precisa','Não é necessário criar uma conta. Descreva sua necessidade e acrescente detalhes e arquivos se desejar.','Seu nome','E-mail','País / região','Sua solicitação e resultado esperado','Adicionar dados da empresa, contato e projeto (opcional)','Anexos','Até 10 arquivos; 20 MB cada; 100 MB no total. JPG, PNG, WebP, PDF, TXT, CSV, DOCX, XLSX, PPTX. Arraste ou selecione arquivos.','Enviar consulta','Enviando…','Recebemos sua consulta. Avaliaremos suas necessidades com atenção e entraremos em contato o mais breve possível.','Número da consulta','Enviar uma consulta não autoriza contato com fornecedores, aceita tarefas, firma contratos nem autoriza pagamentos.','Tenho direito de compartilhar estas informações e concordo com seu uso para avaliar e responder à minha consulta conforme o aviso de privacidade.','Não foi possível concluir o envio. Seus dados permanecem no formulário. Tente novamente ou escreva para support@seekapi.ai.','Remover','Editar dados / iniciar novo envio de arquivos','Empresa','Agente / equipe de IA','Permissões e evidências do agente','Confirmo uso civil lícito e informo todas as partes, usuários finais, destinos e rotas. Não solicito evasão de restrições.'],
 ru:['Расскажите о вашей задаче','Регистрация не требуется. Опишите задачу и при необходимости добавьте сведения и файлы.','Ваше имя','Электронная почта','Страна / регион','Запрос и ожидаемый результат. Укажите стороны, товар, конечное использование и маршрут.','Добавить сведения о компании, контактах и проекте (необязательно)','Вложения','До 10 файлов; по 20 МБ; всего 100 МБ. JPG, PNG, WebP, PDF, TXT, CSV, DOCX, XLSX, PPTX. Перетащите или выберите файлы.','Отправить запрос','Отправка…','Мы получили ваш запрос. Мы внимательно оценим ваши потребности и свяжемся с вами как можно скорее.','Номер запроса','Отправка запроса не разрешает контакт с поставщиками, не означает принятие задачи, заключение договора или разрешение платежа.','Я имею право передавать эти сведения и согласен на их использование для оценки запроса и ответа согласно уведомлению о конфиденциальности.','Отправку не удалось завершить. Данные остались в форме. Повторите попытку или напишите на support@seekapi.ai.','Удалить','Изменить сведения / начать новую загрузку','Компания','Агент / команда ИИ','Полномочия агента и доказательства','Подтверждаю законное гражданское использование и раскрываю все стороны, конечных пользователей, страны назначения и маршруты. Не запрашиваю обход ограничений.']
};
export const copy=Object.fromEntries(Object.entries(rows).map(([locale,row])=>[locale,Object.fromEntries(keys.map((key,i)=>[key,row[i]]))])) as Record<Locale,Record<typeof keys[number],string>>;
export const fieldOrder=['company','website','role','preferred_contact','wechat','whatsapp','phone','telegram','preferred_language','timezone','product','quantity','budget','deadline','destination','suppliers','certification','logistics','nda','allowed_actions','prohibited_actions','required_evidence','approval_contact','task_type'] as const;
const labels:Record<Locale,string[]>={
 en:['Company / project','Website','Your role','Preferred contact method','WeChat ID','WhatsApp','Phone (country code)','Telegram','Preferred language','Time zone','Product / specifications / reference links','Quantity / unit','Budget / currency (or undecided)','Deadline','Delivery destination','Existing suppliers / current issues','Standards / certification / documents','Logistics / warehouse requirements','NDA or confidentiality requirements','Allowed actions','Prohibited actions','Required evidence / completion definition','Human approval contact','Task class (AH01–AH08)'],
 ja:['会社・プロジェクト','ウェブサイト','役職','希望する連絡方法','WeChat ID','WhatsApp','電話（国番号）','Telegram','希望言語','タイムゾーン','製品・仕様・参考リンク','数量・単位','予算・通貨（未定可）','希望期限','納入先','既存サプライヤー・課題','規格・認証・書類','物流・倉庫の要件','NDA・秘密保持の要件','許可する行為','禁止する行為','必要な証拠・完了条件','承認担当者の連絡先','タスク種別（AH01–AH08）'],
 es:['Empresa / proyecto','Sitio web','Su cargo','Medio de contacto preferido','ID de WeChat','WhatsApp','Teléfono (código de país)','Telegram','Idioma preferido','Zona horaria','Producto / especificaciones / enlaces','Cantidad / unidad','Presupuesto / moneda (o por definir)','Fecha límite','Destino de entrega','Proveedores actuales / problemas','Normas / certificaciones / documentos','Requisitos de logística / almacén','Acuerdo de confidencialidad / requisitos','Acciones permitidas','Acciones prohibidas','Evidencias / criterio de finalización','Contacto humano de aprobación','Clase de tarea (AH01–AH08)'],
 ar:['الشركة / المشروع','الموقع الإلكتروني','وظيفتك','وسيلة التواصل المفضلة','معرّف WeChat','WhatsApp','الهاتف (رمز الدولة)','Telegram','اللغة المفضلة','المنطقة الزمنية','المنتج / المواصفات / الروابط','الكمية / الوحدة','الميزانية / العملة (أو غير محددة)','الموعد النهائي','وجهة التسليم','الموردون الحاليون / المشكلات','المعايير / الشهادات / المستندات','متطلبات الشحن / التخزين','اتفاقية السرية / متطلبات السرية','الإجراءات المسموحة','الإجراءات المحظورة','الأدلة المطلوبة / معيار الإنجاز','جهة الاتصال البشرية للموافقة','فئة المهمة (AH01–AH08)'],
 de:['Unternehmen / Projekt','Website','Ihre Position','Bevorzugter Kontaktweg','WeChat-ID','WhatsApp','Telefon (Ländervorwahl)','Telegram','Bevorzugte Sprache','Zeitzone','Produkt / Spezifikation / Links','Menge / Einheit','Budget / Währung (oder offen)','Termin','Lieferziel','Bestehende Lieferanten / Probleme','Normen / Zertifizierung / Unterlagen','Logistik- / Lageranforderungen','NDA / Vertraulichkeit','Erlaubte Handlungen','Verbotene Handlungen','Nachweise / Abschlusskriterien','Menschlicher Freigabekontakt','Aufgabenklasse (AH01–AH08)'],
 'pt-BR':['Empresa / projeto','Site','Seu cargo','Canal de contato preferido','ID do WeChat','WhatsApp','Telefone (código do país)','Telegram','Idioma preferido','Fuso horário','Produto / especificações / links','Quantidade / unidade','Orçamento / moeda (ou a definir)','Prazo','Destino de entrega','Fornecedores atuais / problemas','Normas / certificações / documentos','Requisitos de logística / armazém','Acordo de confidencialidade / requisitos','Ações permitidas','Ações proibidas','Evidências / critérios de conclusão','Contato humano para aprovação','Classe de tarefa (AH01–AH08)'],
 ru:['Компания / проект','Сайт','Ваша должность','Предпочтительный способ связи','WeChat ID','WhatsApp','Телефон (код страны)','Telegram','Предпочтительный язык','Часовой пояс','Товар / характеристики / ссылки','Количество / единица','Бюджет / валюта (или не определён)','Срок','Место доставки','Текущие поставщики / проблемы','Стандарты / сертификаты / документы','Требования к логистике / складу','NDA / конфиденциальность','Разрешённые действия','Запрещённые действия','Доказательства / критерии завершения','Контакт для одобрения человеком','Класс задачи (AH01–AH08)']
};
export function fieldLabel(locale:Locale,key:typeof fieldOrder[number]){return labels[locale][fieldOrder.indexOf(key)];}

export const policyLabels:Record<Locale,string>={en:'Privacy notice',ja:'プライバシー通知',es:'Aviso de privacidad',ar:'إشعار الخصوصية',de:'Datenschutzhinweis','pt-BR':'Aviso de privacidade',ru:'Уведомление о конфиденциальности'};
export const previewLabels:Record<Locale,string>={en:'Preview · Online submission is not connected. Use synthetic test data only.',ja:'プレビュー · オンライン送信は未接続です。架空のテスト情報のみ入力してください。',es:'Vista previa · El envío no está conectado. Utilice solo datos ficticios de prueba.',ar:'معاينة · الإرسال الإلكتروني غير متصل. استخدم بيانات اختبار وهمية فقط.',de:'Vorschau · Die Online-Übermittlung ist noch nicht verbunden. Nur fiktive Testdaten verwenden.','pt-BR':'Prévia · O envio ainda não está conectado. Use apenas dados fictícios de teste.',ru:'Предпросмотр · Онлайн-отправка не подключена. Используйте только вымышленные тестовые данные.'};
