import Link from 'next/link';
import { Eyebrow, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata, siteUrl } from '@/lib/site';
const path='/china-supply-check/connectors';
export const metadata=pageMetadata('Source Electrical Connectors from China: Mating, Pitch and Pack Evidence | SeekAPI','Define exact series, mating half, cavity count, pitch, contacts and packaging before comparing connector listings and supplier quotes.',path);
const schema={'@context':'https://schema.org','@type':'WebPage',name:'China connector sourcing evidence',url:siteUrl+path,about:{'@type':'Thing',name:'Electrical connectors'}};
export default function Page(){return <PageShell>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} />
<section className="page-hero"><div className="container"><Eyebrow>China Supply Check · connectors</Eyebrow><h1>“Compatible connector” needs a mating and contact check.</h1><p>A connector listing may show a housing without terminals, one gender of a pair or a close pitch variant. Identify series/model, mating interface, cavity count, pitch, orientation, latch/keying, contact type, wire gauge or PCB footprint, rating and quantity.</p></div></section>
<section className="section"><div className="container"><SectionTitle eyebrow="Category input" title="Specify the assembly that must arrive."/><div className="definition-grid"><div className="definition"><h3>Mechanical match</h3><p>Record pitch, row count, keyed geometry, mounting style and exact mating part. A similar silhouette cannot prove interchangeability or board footprint fit.</p></div><div className="definition"><h3>Electrical and material</h3><p>Ask for plating, current/voltage and temperature ratings, insulation material and required compliance documents. Badges without traceable documents remain unverified.</p></div><div className="definition"><h3>Pack and MOQ trap</h3><p>Count housings, contacts and assembled sets separately. MOQ 1,000 “pcs” of terminals does not meet 1,000 complete two-part connector sets; reel and bag quantities need explicit conversion.</p></div></div></div></section>
<section className="section section-dark"><div className="container"><SectionTitle eyebrow="Synthetic worked example" title="1,000 complete 2-pin cable-to-board sets, 2.0 mm pitch." body="Synthetic brief, not a verified equivalent part. Include only a listing documenting both mating halves, 2.0 mm pitch and contacts for the specified wire gauge at compatible quantity. Exclude a 2.54 mm family despite a similar photo. Mark a 2.0 mm housing-only offer UNKNOWN for complete sets until terminals and mating half are evidenced. Do not infer certification, substitution compatibility or stock from a title."/><p>Preserve source URL, observation time, currency, unit and tier. Display price may be per loose housing or reel and is not a current quote for 1,000 complete sets. A platform shop is not independently verified as the manufacturer.</p></div></section>
<section className="section"><div className="container"><SectionTitle eyebrow="Human answer" title="What requires supplier response or engineering sign-off?" body="Get a current BOM-level quotation, mating drawing, sample, test documentation, availability and lead time when interchangeability is critical. Engineering must approve replacement; a listing screen cannot certify fit or safety. Supplier outreach is a separately authorized future Live RFQ; no paid run is public."/>
<h2>Agent/AEO answer</h2><p>For “find a China 2-pin 2.0 mm connector set,” the free MCP brief encodes complete set, pitch, mating part, contacts and quantity=1000 sets as hard constraints. Return housing-only, unspecified pitch and unproven equivalent as exclusion or UNKNOWN. ARD and MCP tool metadata describe machine access.</p>
<div className="link-list"><Link className="text-link" href="/china-supply-check">CSC contract</Link><Link className="text-link" href="/china-supply-check/sample">Historical sample and limits</Link><Link className="text-link" href="/for-agents#china-supply-check-mcp">Free MCP prepare</Link><a className="text-link" href="https://seekapi.ai/.well-known/ard.json">ARD manifest</a></div></div></section>
</PageShell>;}
