import Link from 'next/link';
import { Eyebrow, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';

export const metadata = pageMetadata('China Supply Check discovery status', 'Dated public URL, Registry and distribution channel readbacks for SeekAPI China Supply Check.', '/discovery-status');

type State = 'PUBLICLY_DEPLOYED' | 'INDEXED' | 'INDEXED_STALE' | 'UNKNOWN';
type Surface = { name: string; state: State; address: string; url?: string; checked: string; evidence: string; blocker: string };
const surfaces: Surface[] = [
  { name: 'CSC product page', state: 'PUBLICLY_DEPLOYED', address: 'https://seekapi.ai/china-supply-check', url: 'https://seekapi.ai/china-supply-check', checked: 'Dated snapshot · read live before purchase', evidence: 'https://seekapi.ai/china-supply-check', blocker: 'Brand-blind search indexing not yet evidenced.' },
  { name: 'Production acceptance summary', state: 'PUBLICLY_DEPLOYED', address: 'https://seekapi.ai/china-supply-check/sample', url: 'https://seekapi.ai/china-supply-check/sample', checked: 'Authorized production acceptance summary', evidence: 'https://seekapi.ai/china-supply-check/sample', blocker: 'Candidate-level supplier details are not disclosed; archived V4 example is secondary.' },
  { name: 'Public CSC MCP', state: 'PUBLICLY_DEPLOYED', address: 'https://api.seekapi.ai/mcp · discover/prepare free', url: 'https://api.seekapi.ai/mcp', checked: 'Live discovery tool readback', evidence: 'https://api.seekapi.ai/mcp', blocker: 'Status/result require independent signed wallet authentication bound to the settled order.' },
  { name: 'Official MCP Registry', state: 'INDEXED', address: 'io.github.kiddhu/seekapi · dated Registry snapshot', url: 'https://registry.modelcontextprotocol.io/v0.1/servers/io.github.kiddhu%2Fseekapi/versions/latest', checked: '2026-10-08 09:37:00Z · v0.1.7 active and latest', evidence: 'https://registry.modelcontextprotocol.io/v0.1/servers/io.github.kiddhu%2Fseekapi/versions/latest', blocker: 'Fresh latest-version readback returned active 0.1.7. Historical immutable versions remain separate; third-party mirrors and brand-blind retrieval may still be stale or absent.' },
  { name: 'ARD v0.91 host', state: 'PUBLICLY_DEPLOYED', address: 'https://seekapi.ai/.well-known/ard.json · urn:air:seekapi.ai:api:china-supply-check-v0', url: 'https://seekapi.ai/.well-known/ard.json', checked: 'Public 200', evidence: 'https://seekapi.ai/.well-known/ard.json', blocker: 'Generic brand-blind search unproven.' },
  { name: 'MCP Harbor', state: 'INDEXED_STALE', address: 'io.github.kiddhu/seekapi · 0.1.5', url: 'https://ai.mcpharbor.dev/servers/io.github.kiddhu/seekapi', checked: '2026-10-04 11:43:51Z', evidence: 'https://ai.mcpharbor.dev/api/v0/servers/io.github.kiddhu%2Fseekapi', blocker: 'An existing official-registry mirror was observed at 0.1.5 while the official latest was 0.1.6. Refresh and brand-blind discovery are not confirmed.' },
  { name: 'Glama', state: 'INDEXED', address: 'SeekAPI China Supply Check connector', url: 'https://glama.ai/mcp/connectors/io.github.kiddhu/seekapi', checked: '2026-10-04 11:48:39Z', evidence: 'https://glama.ai/mcp/connectors/io.github.kiddhu/seekapi', blocker: 'Current commercial description and public repository were present. Numeric registry version was not exposed in the observed page. Listing and health checks do not establish procurement-intent ranking or traffic.' },
  { name: 'PluginBench', state: 'INDEXED_STALE', address: 'Existing listing 0.1.4 · correction SUBMITTED / PENDING_REVIEW', url: 'https://pluginbench.com/mcp/io.github.kiddhu/seekapi', checked: '2026-10-04 · stale listing read at 11:44:00Z; later correction acknowledged by submission form', evidence: 'https://pluginbench.com/mcp/io.github.kiddhu/seekapi', blocker: 'The observed listing still said paid check closed. A correction was submitted and acknowledged for review; no submission ID was exposed. Current indexing of the correction has not been confirmed.' },
  { name: 'MCPServers.org', state: 'UNKNOWN', address: 'Free remote-server submission route available', checked: '2026-10-04 · public form readback', evidence: 'https://mcpservers.org/submit', blocker: 'The form accepts a website or documentation URL and remote connections. No accepted submission or current listing is evidenced in this snapshot.' },
  { name: 'A2A Registry', state: 'UNKNOWN', address: 'No matching record in the bounded SeekAPI query', checked: '2026-10-04 11:43:48Z', evidence: 'https://api.a2a-registry.org/public/agents?q=seekapi', blocker: 'The bounded query returned no matches. This is not proof of universal absence; compatible truthful manifest eligibility and submission remain unconfirmed.' },
  { name: 'Smithery', state: 'UNKNOWN', address: 'Remote MCP publishing available; no listing receipt', checked: '2026-10-04 · publishing documentation and login redirect readback', evidence: 'https://smithery.ai/docs/build/publish', blocker: 'Streamable HTTP URL publishing is documented, but the observed publishing route requires account login. No submission or listing ID is claimed.' },
  { name: 'x402 Bazaar', state: 'UNKNOWN', address: 'No CSC resource/listing ID', checked: '2026-10-04 08:08:33Z · official merchant endpoint GET 200, resources empty', evidence: 'https://docs.cdp.coinbase.com/x402/seller/get-discovered', blocker: 'Indexing is triggered by official metadata plus settled payment, not a registration form; no submission or listing ID exists.' },
  { name: 'Claude directory/connector', state: 'UNKNOWN', address: 'No connector or directory listing ID', checked: '2026-10-04 · current submission page and developer portal read', evidence: 'https://claude.com/docs/connectors/building/submission', blocker: 'ACCOUNT_LOGIN_REQUIRED: developer portal redirects to login; no submission or listing ID exists. Paid-plan and reviewer access are unverified. Financial transaction capability needs an express written determination; no submission or review approval is claimed.' },
  { name: 'OpenAI App/MCP directory', state: 'UNKNOWN', address: 'No submission/listing ID', checked: 'Portal redirects to account login', evidence: 'https://platform.openai.com/plugins', blocker: 'ACCOUNT_LOGIN_REQUIRED: no submission ID exists. Current official guidelines prohibit selling digital services through plugins; this paid screening flow also has a scoped eligibility gate.' },
];

export default function DiscoveryStatusPage() {
  return <PageShell>
    <section className="page-hero"><div className="container"><Eyebrow>Discovery status · dated snapshot</Eyebrow><h1>China Supply Check distribution status</h1><p>This snapshot separates a reachable public URL from a listing that an unknown Agent can find. It is a thin projection of public endpoints and platform readbacks; it does not demonstrate successful procurement-intent discovery.</p><div className="button-row"><Link className="button button-ghost" href="/china-supply-check">CSC product</Link><Link className="button button-ghost" href="/china-supply-check/sample">Sample summary</Link></div></div></section>
    <section className="section"><div className="container"><SectionTitle eyebrow="Outside-in ledger" title="A reachable URL is not a directory listing" body="PUBLICLY_DEPLOYED means the URL responds. INDEXED means an actual record was read; INDEXED_STALE means that record contains old facts. SUBMITTED is a separate receipt, never proof of corrected indexing. UNKNOWN preserves missing evidence. Listing counts and health checks do not prove user traffic or brand-blind ranking."/><div className="grid-2">{surfaces.map(x=><article className="feature-card" key={x.name}><span className="feature-index">{x.state}</span><h3>{x.name}</h3><p>{x.url?<a className="text-link" href={x.url}>{x.address}</a>:x.address}</p><p>Last outside-in check: {x.checked}</p><p>Exact limit: {x.blocker}</p><a className="text-link" href={x.evidence}>Public evidence or official mechanism</a></article>)}</div></div></section>
    <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Pre-publication discovery baseline · 29 September 2026" title="No CSC-specific web discovery observed in the frozen short-query capture." body="The preregistered 25 positive queries produced zero observed canonical CSC page or listing hits in one public web search response per query. This is not a top-20 SEO audit, a two-day stable score or a cross-platform Agent acceptance; that capture did not establish directory submission IDs. Exact-brand T06 surfaced a stale SeekAPI root-page snippet, not a CSC result."/><p>The pre-publication baseline is historical. Publication-time independent discovery is measured separately.</p></div></section>
  </PageShell>;
}
