import Link from 'next/link';
import { Eyebrow, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';

export const metadata = pageMetadata('China Supply Check discovery status', 'Dated public URL, Registry and distribution channel readbacks for SeekAPI China Supply Check.', '/discovery-status');

type State = 'PUBLICLY_DEPLOYED' | 'UNKNOWN';
type Surface = { name: string; state: State; address: string; url?: string; checked: string; evidence: string; blocker: string };
const surfaces: Surface[] = [
  { name: 'CSC product page', state: 'PUBLICLY_DEPLOYED', address: 'https://seekapi.ai/china-supply-check', url: 'https://seekapi.ai/china-supply-check', checked: 'Dated snapshot · read live before purchase', evidence: 'https://seekapi.ai/china-supply-check', blocker: 'Brand-blind search indexing not yet evidenced.' },
  { name: 'Production acceptance summary', state: 'PUBLICLY_DEPLOYED', address: 'https://seekapi.ai/china-supply-check/sample', url: 'https://seekapi.ai/china-supply-check/sample', checked: 'Authorized production acceptance summary', evidence: 'https://seekapi.ai/china-supply-check/sample', blocker: 'Candidate-level supplier details are not disclosed; archived V4 example is secondary.' },
  { name: 'Public CSC MCP', state: 'PUBLICLY_DEPLOYED', address: 'https://api.seekapi.ai/mcp · discover/prepare free', url: 'https://api.seekapi.ai/mcp', checked: 'Live discovery tool readback', evidence: 'https://api.seekapi.ai/mcp', blocker: 'Status/result require independent signed wallet authentication bound to the settled order.' },
  { name: 'Official MCP Registry', state: 'PUBLICLY_DEPLOYED', address: 'io.github.kiddhu/seekapi · dated Registry snapshot', url: 'https://registry.modelcontextprotocol.io/v0.1/servers/io.github.kiddhu%2Fseekapi/versions/latest', checked: '2026-10-04 09:54:10Z · v0.1.6 active and latest', evidence: 'https://registry.modelcontextprotocol.io/v0.1/servers/io.github.kiddhu%2Fseekapi/versions/latest', blocker: 'Protected OIDC publication succeeded; exact 0.1.6 and latest both returned active. Historical immutable versions remain separate; third-party indexing is not implied.' },
  { name: 'ARD v0.91 host', state: 'PUBLICLY_DEPLOYED', address: 'https://seekapi.ai/.well-known/ard.json · urn:air:seekapi.ai:api:china-supply-check-v0', url: 'https://seekapi.ai/.well-known/ard.json', checked: 'Public 200', evidence: 'https://seekapi.ai/.well-known/ard.json', blocker: 'Generic brand-blind search unproven.' },
  { name: 'x402 Bazaar', state: 'UNKNOWN', address: 'No CSC resource/listing ID', checked: '2026-10-04 08:08:33Z · official merchant endpoint GET 200, resources empty', evidence: 'https://docs.cdp.coinbase.com/x402/seller/get-discovered', blocker: 'Indexing is triggered by official metadata plus settled payment, not a registration form; no submission or listing ID exists.' },
  { name: 'Claude directory/connector', state: 'UNKNOWN', address: 'No connector or directory listing ID', checked: '2026-10-04 · current submission page and developer portal read', evidence: 'https://claude.com/docs/connectors/building/submission', blocker: 'ACCOUNT_LOGIN_REQUIRED: developer portal redirects to login; no submission or listing ID exists. Paid-plan and reviewer access are unverified. Financial transaction capability needs an express written determination; no submission or review approval is claimed.' },
  { name: 'OpenAI App/MCP directory', state: 'UNKNOWN', address: 'No submission/listing ID', checked: 'Portal redirects to account login', evidence: 'https://platform.openai.com/plugins', blocker: 'ACCOUNT_LOGIN_REQUIRED: no submission ID exists. Current official guidelines prohibit selling digital services through plugins; this paid screening flow also has a scoped eligibility gate.' },
];

export default function DiscoveryStatusPage() {
  return <PageShell>
    <section className="page-hero"><div className="container"><Eyebrow>Discovery status · dated snapshot</Eyebrow><h1>China Supply Check distribution status</h1><p>This snapshot separates a reachable public URL from a listing that an unknown Agent can find. It is a thin projection of public endpoints and platform readbacks; it creates no order or control plane.</p><div className="button-row"><Link className="button button-ghost" href="/china-supply-check">CSC product</Link><Link className="button button-ghost" href="/china-supply-check/sample">Sample summary</Link></div></div></section>
    <section className="section"><div className="container"><SectionTitle eyebrow="Outside-in ledger" title="A reachable URL is not a directory listing" body="PUBLICLY_DEPLOYED means the URL responds; UNKNOWN means the channel has no evidenced submission or listing. Each channel is reported independently; no single global PASS is claimed."/><div className="grid-2">{surfaces.map(x=><article className="feature-card" key={x.name}><span className="feature-index">{x.state}</span><h3>{x.name}</h3><p>{x.url?<a className="text-link" href={x.url}>{x.address}</a>:x.address}</p><p>Last outside-in check: {x.checked}</p><p>Exact limit: {x.blocker}</p><a className="text-link" href={x.evidence}>Public evidence or official mechanism</a></article>)}</div></div></section>
    <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Pre-publication discovery baseline · 29 September 2026" title="No CSC-specific web discovery observed in the frozen short-query capture." body="The preregistered 25 positive queries produced zero observed canonical CSC page or listing hits in one public web search response per query. This is not a top-20 SEO audit, a two-day stable score or a cross-platform Agent acceptance; pending directory channels have no listing IDs. Exact-brand T06 surfaced a stale SeekAPI root-page snippet, not a CSC result."/><p>The pre-publication baseline is historical. Publication-time independent discovery is measured separately.</p></div></section>
  </PageShell>;
}
