import Link from 'next/link';
import { Eyebrow, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';

export const metadata = pageMetadata('China Supply Check discovery status', 'Public URLs, exact platform listing state and preregistered pre-publication baseline for SeekAPI China Supply Check.', '/discovery-status');

type State = 'ENGINEERING_READY' | 'PUBLICLY_DEPLOYED' | 'OUTSIDE_IN_DISCOVERED' | 'WAIT_EXTERNAL_REVIEW' | 'BLOCKED_EXACT_GATE' | 'FAIL';
type Surface = { name: string; state: State; address: string; url?: string; checked: string; evidence: string; blocker: string };
const surfaces: Surface[] = [
  { name: 'CSC product page', state: 'PUBLICLY_DEPLOYED', address: 'https://seekapi.ai/china-supply-check', url: 'https://seekapi.ai/china-supply-check', checked: '2026-09-29 12:19 UTC · HTTP 200', evidence: 'https://github.com/kiddhu/aion-governance/issues/1034#issuecomment-5890177629', blocker: 'Brand-blind search indexing not yet evidenced.' },
  { name: 'Historical V4-prefix sample report', state: 'PUBLICLY_DEPLOYED', address: 'https://seekapi.ai/china-supply-check/sample', url: 'https://seekapi.ai/china-supply-check/sample', checked: '2026-09-29 12:19 UTC · HTTP 200', evidence: 'https://github.com/kiddhu/aion-governance/issues/1034#issuecomment-5890177629', blocker: 'Historical full V4 run TECHNICAL_BLOCKED; not a completed paid customer order. Brand-blind search unproven.' },
  { name: 'Remote MCP non-value', state: 'PUBLICLY_DEPLOYED', address: 'https://api.seekapi.ai/mcp · seekapi-factory/0.1.2', url: 'https://api.seekapi.ai/mcp', checked: '2026-09-29 12:39 UTC · external MCP initialize/list/prepare', evidence: 'https://github.com/kiddhu/aion-governance/issues/1034#issuecomment-5890488865', blocker: 'Status/result deny until a settled-order proof read service is armed; paid run is absent.' },
  { name: 'Official MCP Registry', state: 'BLOCKED_EXACT_GATE', address: 'io.github.kiddhu/seekapi · latest public v0.1.1', url: 'https://registry.modelcontextprotocol.io/v0.1/servers/io.github.kiddhu%2Fseekapi/versions/latest', checked: '2026-09-29 12:49 UTC · public listing v0.1.1', evidence: 'https://github.com/kiddhu/aion-governance/issues/1034#issuecomment-5890636523', blocker: 'Reviewed v0.1.3 merged but unpublished; repository admin must establish/read back protected publisher environment and seekapi-v* tag controls.' },
  { name: 'ARD v0.91 host', state: 'PUBLICLY_DEPLOYED', address: 'https://seekapi.ai/.well-known/ard.json · urn:air:seekapi.ai:api:china-supply-check-v0', url: 'https://seekapi.ai/.well-known/ard.json', checked: '2026-09-29 12:32 UTC · public 200, official publisher conformance PASS with ARD User-Agent', evidence: 'https://github.com/kiddhu/aion-governance/issues/1034#issuecomment-5890381084', blocker: 'Generic brand-blind search unproven; default Python-urllib User-Agent receives Cloudflare 403.' },
  { name: 'x402 Bazaar', state: 'BLOCKED_EXACT_GATE', address: 'No CSC resource/listing ID', checked: '2026-09-29 12:35 UTC · official mechanism readback', evidence: 'https://docs.cdp.coinbase.com/x402/seller/get-discovered', blocker: 'A real 2.99 USDC CDP-facilitator x402 purchase route and accepted-order result path are required before a CSC listing can be indexed.' },
  { name: 'Claude directory/connector', state: 'BLOCKED_EXACT_GATE', address: 'No connector or directory listing ID', checked: '2026-09-29 12:35 UTC · official portal mechanism readback', evidence: 'https://claude.com/blog/build-plugins-for-claude', blocker: 'A paid Claude-plan developer must connect/test the remote MCP and submit in the directory portal; no account receipt exists.' },
  { name: 'OpenAI MCP-backed plugin', state: 'BLOCKED_EXACT_GATE', address: 'No submission/listing ID', checked: '2026-09-29 12:35 UTC · official submission mechanism readback', evidence: 'https://developers.openai.com/plugins/deploy/submission', blocker: 'Verified publisher identity, Apps Management write, domain/policy materials and portal submission are not evidenced.' },
];

export default function DiscoveryStatusPage() {
  return <PageShell>
    <section className="page-hero"><div className="container"><Eyebrow>Owner discovery dashboard · evidence snapshot</Eyebrow><h1>China Supply Check distribution status</h1><p>This snapshot separates a reachable public URL from a listing that an unknown Agent can find. It is a thin projection of public endpoints, platform readbacks and the durable GitHub checkpoints; it creates no order or control plane.</p><div className="button-row"><Link className="button button-ghost" href="/china-supply-check">CSC product</Link><Link className="button button-ghost" href="/china-supply-check/sample">Sample report</Link></div></div></section>
    <section className="section"><div className="container"><SectionTitle eyebrow="Outside-in ledger" title="A PR merge is not a directory listing" body="States use the frozen D2 vocabulary. PUBLICLY_DEPLOYED means the URL responds; OUTSIDE_IN_DISCOVERED requires a clean brand-blind platform discovery path and is not claimed here."/><div className="grid-2">{surfaces.map(x=><article className="feature-card" key={x.name}><span className="feature-index">{x.state}</span><h3>{x.name}</h3><p>{x.url?<a className="text-link" href={x.url}>{x.address}</a>:x.address}</p><p>Last outside-in check: {x.checked}</p><p>Exact limit: {x.blocker}</p><a className="text-link" href={x.evidence}>Evidence or official mechanism</a></article>)}</div></div></section>
    <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Pre-publication discovery baseline · 29 September 2026" title="No CSC-specific web discovery observed in the frozen short-query capture." body="The preregistered 25 positive queries produced zero observed canonical CSC page or listing hits in one public web search response per query. The 22 brand-blind subset also had zero observed hits. This is not a top-20 SEO audit, a two-day stable score or a cross-platform Agent acceptance; pending directory channels have no listing IDs. Exact-brand T06 surfaced a stale SeekAPI root-page snippet, not a CSC result."/><a className="text-link" href="https://github.com/kiddhu/aion-governance/blob/work/csc-agent-discovery-v2/docs/discussions/csc-agent-discovery-v2/CSC_BENCHMARK_PREPUBLICATION_BASELINE_V1.md">Benchmark method and raw evidence</a></div></section>
  </PageShell>;
}
