import Link from 'next/link';
import { Eyebrow, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';

export const metadata = pageMetadata(
  'How China Supply Check Screens MOQ and Specifications | SeekAPI',
  'See how a product/model, quantity and must-have requirements are compared with China B2B listing evidence, duplicates, mismatches and unknowns.',
  '/china-supply-check/moq-specification-screening',
);

export default function Page() { return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>China Supply Check · screening method</Eyebrow><h1>A shortlist should explain why each candidate fits.</h1><p>Give a written product or model, quantity and unit, and the specifications that cannot change. SeekAPI's bounded check screens item evidence, minimum order quantity and distinct documented platform shops. A successful completed report has three evidence-backed supplier candidates worth advancing to RFQ; a shortage remains a shortage.</p></div></section>
  <section className="section"><div className="container"><p>Supplier RFQ-worthiness and exact product qualification are separate. The successful check delivers three evidence-backed supplier candidates worth advancing to RFQ; exact product specifications and requested-quantity fit are reported with their supporting evidence or remaining gaps.</p><SectionTitle eyebrow="Decision rules" title="Match, mismatch or UNKNOWN."/><div className="definition-grid"><div className="definition"><h3>Product and hard specs</h3><p>Compare the stated material, model, variant and dimension with the buyer requirements. Report supported matches, contradictions and missing evidence separately; a similar photo or broad title is not proof of an exact grade or certification.</p></div><div className="definition"><h3>MOQ and unit</h3><p>Compare the listing's minimum with the buyer quantity only when the units are compatible. A quoted pack and a requested piece count need a known conversion; an unsupported conversion stays UNKNOWN.</p></div><div className="definition"><h3>Distinct shops</h3><p>Multiple product offers from one documented B2B shop are one shop candidate. Company-registration and production-versus-trade identity evidence is reported per candidate when the listing or a bound source provides it; fields without such evidence are marked for that candidate.</p></div><div className="definition"><h3>Exclusions</h3><p>Show duplicates, hard mismatches and near misses with reasons. Missing attributes remain explicit gaps for the relevant candidate, including questions for RFQ. Do not invent supporting evidence or pad the three-candidate success count.</p></div></div></div></section>
  <section className="section section-dark"><div className="container"><SectionTitle eyebrow="Evidence in practice" title="Read the sample summary and the separately archived example." body="The production acceptance summary records an authorized completed paid check. The separately archived historical V4 prefix is preserved for provenance; it does not demonstrate a completed customer paid check."/><div className="link-list"><Link className="text-link" href="/china-supply-check/sample">Read the sample summary</Link><Link className="text-link" href="/china-supply-check/listing-price-vs-quote">Understand observed price</Link></div></div></section>
</PageShell>; }
