import { CTA, Eyebrow, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';
export const metadata=pageMetadata('Trust, Data and Commercial Roles','SeekAPI boundaries for authorization, evidence, quality, data, payment and commercial roles.','/trust');
export default function Page(){return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>Trust model</Eyebrow><h1>Control should survive the handoff.</h1><p>Trust starts with a clear role, limited authority and evidence that matches the claim. This preview describes the operating policy; customer-file storage and transactional controls require separate verification before they are enabled.</p></div></section>
  <section className="section" id="data-ip"><div className="container"><SectionTitle eyebrow="Data and IP" title="Share only what the next decision needs."/><div className="definition-grid"><div className="definition"><h3>Discuss</h3><p>Problem, use case and non-sensitive context. No drawing upload is enabled.</p></div><div className="definition"><h3>Internal review</h3><p>A limited specification may be reviewed without permission to forward it.</p></div><div className="definition"><h3>External RFQ</h3><p>Requires a named recipient, approved file and revision, purpose and forwarding boundary.</p></div><div className="definition"><h3>Current status</h3><p>The manufacturing-file storage, retention, deletion and external-model controls are pending verification before transactional launch.</p></div></div></div></section>
  <section className="section section-dark" id="quality"><div className="container"><SectionTitle eyebrow="Quality" title="Evidence is scoped to the question." body="A sample does not guarantee a production batch. Inspection coordination does not transfer design, safety or regulatory responsibility. The agreed revision, critical characteristics, evidence producer, limitations and corrective actions remain visible."/></div></section>
  <section className="section" id="commercial-role"><div className="container"><SectionTitle eyebrow="Commercial role" title="Know what SeekAPI is being paid to do."/><div className="grid-3"><div className="definition"><h3>Service provider</h3><p>A project fee or monthly scope-based fee covers agreed execution. Historical purchase price is not required to calculate the normal service fee.</p></div><div className="definition"><h3>Seller of goods</h3><p>If SeekAPI is the seller, that role and the product price are stated explicitly for that workstream.</p></div><div className="definition"><h3>Third-party coordination</h3><p>Inspection, samples, laboratories, freight or site work are pre-approved and kept distinct from SeekAPI fees.</p></div></div></div></section>
  <section className="section section-dark" id="payments"><div className="container"><SectionTitle eyebrow="Payments" title="No checkout is active in this preview." body="A payment rail will be shown as available only after the responsible entity, account, terms and operating controls are verified. Payment tools do not by themselves guarantee product quality or resolve every dispute."/></div></section>
  <section className="section" id="regulated-work"><div className="container"><SectionTitle eyebrow="Qualified-provider boundary" title="Coordination is not a substitute for a required license." body="SeekAPI can map requirements, compare providers, coordinate documents, monitor milestones and preserve evidence. Legal opinions, tax filings, audits, certifications, laboratory reports, customs declarations, regulated transport and other licensed work are performed only by the customer or an appropriately qualified provider. SeekAPI does not guarantee regulatory approval, customs release, tax treatment, certification, transit time or legal outcome."/><div className="link-list"><a className="text-link" href="/china-compliance-logistics">Compliance, market entry and fulfillment</a></div></div></section>
  <section className="section section-dark" id="who-we-are"><div className="container"><SectionTitle eyebrow="Who operates SeekAPI" title="A public brand with a named legal operator." body="SeekAPI is operated by SeekAPI Technology Limited, a company based in Hong Kong."/><div className="definition-grid"><div className="definition"><h3>Legal entity</h3><p>SeekAPI Technology Limited</p></div><div className="definition"><h3>Registered / contact address</h3><p>Room P11, Flat 2C, 2/F, Hung To Ctr., 94–96 How Ming St., Kwun Tong, Kowloon, Hong Kong</p></div><div className="definition"><h3>Customer support</h3><p><a className="text-link" href="mailto:support@seekapi.ai">support@seekapi.ai</a></p></div><div className="definition"><h3>Before sharing sensitive information</h3><p>Contact us first to confirm service scope, handling, recipients and the responsible provider.</p></div></div></div></section>
  <CTA title="Start with a small trust test." body="Describe one non-sensitive issue and expand permission only when the next step requires it." primaryHref="/start" secondaryLabel="See proof labels" secondaryHref="/proof"/>
</PageShell>}
