import { CTA, Eyebrow, PageShell, SectionTitle } from '@/components/site';
import { pageMetadata } from '@/lib/site';
export const metadata=pageMetadata('Trust, Data and Commercial Roles','SeekAPI boundaries for authorization, evidence, quality, data, payment and commercial roles.','/trust');
export default function Page(){return <PageShell>
  <section className="page-hero"><div className="container"><Eyebrow>Trust model</Eyebrow><h1>Control should survive the handoff.</h1><p>Trust starts with a clear role, limited authority and evidence that matches the claim. This preview describes the operating policy; customer-file storage and transactional controls require separate verification before they are enabled.</p></div></section>
  <section className="section" id="data-ip"><div className="container"><SectionTitle eyebrow="Data and IP" title="Share only what the next decision needs."/><div className="definition-grid"><div className="definition"><h3>Discuss</h3><p>Problem, use case and non-sensitive context. No drawing upload is enabled.</p></div><div className="definition"><h3>Internal review</h3><p>A limited specification may be reviewed without permission to forward it.</p></div><div className="definition"><h3>External RFQ</h3><p>Requires a named recipient, approved file and revision, purpose and forwarding boundary.</p></div><div className="definition"><h3>Current status</h3><p>The manufacturing-file storage, retention, deletion and external-model controls are pending verification before transactional launch.</p></div></div></div></section>
  <section className="section section-dark" id="quality"><div className="container"><SectionTitle eyebrow="Quality" title="Evidence is scoped to the question." body="A sample does not guarantee a production batch. Inspection coordination does not transfer design, safety or regulatory responsibility. The agreed revision, critical characteristics, evidence producer, limitations and corrective actions remain visible."/></div></section>
  <section className="section" id="commercial-role"><div className="container"><SectionTitle eyebrow="Commercial role" title="Know what SeekAPI is being paid to do."/><div className="grid-3"><div className="definition"><h3>Service provider</h3><p>A project fee or monthly scope-based fee covers agreed execution. Historical purchase price is not required to calculate the normal service fee.</p></div><div className="definition"><h3>Seller of goods</h3><p>If SeekAPI is the seller, that role and the product price are stated explicitly for that workstream.</p></div><div className="definition"><h3>Third-party coordination</h3><p>Inspection, samples, laboratories, freight or site work are pre-approved and kept distinct from SeekAPI fees.</p></div></div></div></section>
  <section className="section section-dark" id="payments"><div className="container"><SectionTitle eyebrow="Payments" title="No checkout is active in this preview." body="A payment rail will be shown as available only after the responsible entity, account, terms and operating controls are verified. Payment tools do not by themselves guarantee product quality or resolve every dispute."/></div></section>
  <section className="section" id="who-we-are"><div className="container"><SectionTitle eyebrow="Who is responsible" title="Public identity fields remain evidence-gated." body="SeekAPI is the public brand. Legal entity details, responsible people, operating locations and contact routes must be verified and approved for this rebuilt site before public informational launch. This preview does not invent them."/></div></section>
  <CTA title="Start with a small trust test." body="Describe one non-sensitive issue and expand permission only when the next step requires it." primaryHref="/start" secondaryLabel="See proof labels" secondaryHref="/proof"/>
</PageShell>}
